//
//  DrawingTask.swift
//  
//
//  Created by Ethan Marshall on 4/7/22.
//

import Foundation

/// In the context of a game, the action the player must take to score points.
nonisolated struct DrawingTask: Equatable, Codable, Sendable {
    
    // MARK: Variables
    /// The specific object the user must perform the action for during a game.
    var object: String
    /// The English phrase that should follow this task's type's verb.
    var commandPhrase: String
    /// A generic description of the task's object for use in Clued In mode.
    var genericDescription: String
    /// An emoji which represents this task's object.
    var emoji: String
    
    // MARK: Computed Properties
    /// An English phrase prompting the user to complete the task.
    var commandPrompt: String {
        var answer = "Draw "
        answer += commandPhrase
        return answer
    }
    
    // MARK: Included App Data
    /// The list of all possible tasks for use in games.
    static let taskList: [DrawingTask] = [
        DrawingTask(object: "Aircraft Carrier", commandPhrase: "an aircraft carrier!", genericDescription: "Draw something that carries planes!", emoji: "🛬"),
        DrawingTask(object: "Airplane", commandPhrase: "an airplane!", genericDescription: "Draw something that flies!", emoji: "🛩"),
        DrawingTask(object: "Alarm Clock", commandPhrase: "an alarm clock!", genericDescription: "Draw something thst rings!", emoji: "⏰"),
        DrawingTask(object: "Ambulance", commandPhrase: "an ambulance", genericDescription: "Draw something with sirens!", emoji: "🚑"),
        DrawingTask(object: "Angel", commandPhrase: "an angel!", genericDescription: "Draw something with a halo!", emoji: "😇"),
        DrawingTask(object: "Animal Migration", commandPhrase: "an animal migration", genericDescription: "Draw a movement of animals!", emoji: "🦬"),
        DrawingTask(object: "Ant", commandPhrase: "an ant!", genericDescription: "Draw a small insect!", emoji: "🐜"),
        DrawingTask(object: "Anvil", commandPhrase: "an anvil!", genericDescription: "Draw a heavy steel tool!", emoji: "🔨"),
        DrawingTask(object: "Apple", commandPhrase: "an apple!", genericDescription: "Draw something round and edible!", emoji: "🍎"),
        DrawingTask(object: "Arm", commandPhrase: "an arm!", genericDescription: "Draw a body part!", emoji: "💪"),
        DrawingTask(object: "Asparagus", commandPhrase: "an asparagus", genericDescription: "Draw a green veggie!", emoji: "🥬"),
        DrawingTask(object: "Axe", commandPhrase: "an axe!", genericDescription: "Draw something that chops!", emoji: "⛏"),
        DrawingTask(object: "Backpack", commandPhrase: "a backpack!", genericDescription: "Draw a strapped container!", emoji: "🎒"),
        DrawingTask(object: "Banana", commandPhrase: "a banana!", genericDescription: "Draw a yellow food!", emoji: "🍌"),
        DrawingTask(object: "Bandage", commandPhrase: "a bandage!", genericDescription: "Draw a adhesive healer!", emoji: "🩹"),
        DrawingTask(object: "Barn", commandPhrase: "a barn!", genericDescription: "Draw a farm building!", emoji: "🧑‍🌾"),
        DrawingTask(object: "Baseball", commandPhrase: "a baseball!", genericDescription: "Draw a sports ball!", emoji: "⚾️"),
        DrawingTask(object: "Baseball Bat", commandPhrase: "a baseball bat!", genericDescription: "Draw a long sports instrument!", emoji: "🏏"),
        DrawingTask(object: "Basket", commandPhrase: "a basket!", genericDescription: "Draw a carrier of objects!", emoji: "🗑"),
        DrawingTask(object: "Basketball", commandPhrase: "a basketball!", genericDescription: "Draw a sports ball!", emoji: "🏀"),
        DrawingTask(object: "Bat", commandPhrase: "a bat!", genericDescription: "Draw a long stick-like object!", emoji: "🏑"),
        DrawingTask(object: "Bathtub", commandPhrase: "a bathtub!", genericDescription: "Draw something from the bathroom!", emoji: "🛁"),
        DrawingTask(object: "Beach", commandPhrase: "a beach!", genericDescription: "Draw a vacation destination!", emoji: "🏖"),
        DrawingTask(object: "Bear", commandPhrase: "a bear!", genericDescription: "Draw a scary animal!", emoji: "🐻"),
        DrawingTask(object: "Beard", commandPhrase: "a beard!", genericDescription: "Draw facial hair!", emoji: "🧔"),
        DrawingTask(object: "Bed", commandPhrase: "a bed!", genericDescription: "Draw a sleeping spot!", emoji: "🛏"),
        DrawingTask(object: "Bee", commandPhrase: "a bee!", genericDescription: "Draw a hurtful insect!", emoji: "🐝"),
        DrawingTask(object: "Belt", commandPhrase: "a belt!", genericDescription: "Draw a pants accessory!", emoji: "🥋"),
        DrawingTask(object: "Bench", commandPhrase: "a bench!", genericDescription: "Draw a place to sit!", emoji: "🪑"),
        DrawingTask(object: "Bicycle", commandPhrase: "bicycle", genericDescription: "Draw a mode of transportation!", emoji: "🚲"),
        DrawingTask(object: "Binoculars", commandPhrase: "a pair of binoculars!", genericDescription: "Draw vision enhancers!", emoji: "🥽"),
        DrawingTask(object: "Birthday Cake", commandPhrase: "a birthday cake!", genericDescription: "Draw a special dessert!", emoji: "🎂"),
        DrawingTask(object: "Blackberry", commandPhrase: "a blackberry!", genericDescription: "Draw a kind of phone!", emoji: "🫐"),
        DrawingTask(object: "Blueberry", commandPhrase: "a blueberry!", genericDescription: "Draw a small fruit!", emoji: "🫐"),
        DrawingTask(object: "Book", commandPhrase: "a book!", genericDescription: "Draw a vessel for information!", emoji: "📖"),
        DrawingTask(object: "Boomerang", commandPhrase: "a boomerang!", genericDescription: "Draw something that always comes back!", emoji: "🪃"),
        DrawingTask(object: "Bottlecap", commandPhrase: "a bottlecap!", genericDescription: "Draw a drink topper!", emoji: "🍾"),
        DrawingTask(object: "Bracelet", commandPhrase: "a bracelet!", genericDescription: "Draw a wrist accessory!", emoji: "💍"),
        DrawingTask(object: "Brain", commandPhrase: "a brain!", genericDescription: "Draw a hidden body part!", emoji: "🧠"),
        DrawingTask(object: "Bread", commandPhrase: "a piece of bread!", genericDescription: "Draw a carbohydrate snack!", emoji: "🍞"),
        DrawingTask(object: "Bridge", commandPhrase: "a bridge!", genericDescription: "Draw a river crossing!", emoji: "🌉"),
        DrawingTask(object: "Broccoli", commandPhrase: "a piece of broccoli!", genericDescription: "Draw a green, leafy veggie!", emoji: "🥦"),
        DrawingTask(object: "Bucket", commandPhrase: "a bucket!", genericDescription: "Draw a metal container!", emoji: "🪣"),
        DrawingTask(object: "Bulldozer", commandPhrase: "a bulldozer!", genericDescription: "Draw construction equipment!", emoji: "🚜"),
        DrawingTask(object: "Bus", commandPhrase: "a bus!", genericDescription: "Draw a group transportation mode!", emoji: "🚍"),
        DrawingTask(object: "Bush", commandPhrase: "a bush!", genericDescription: "Draw a decorative plant!", emoji: "🌳"),
        DrawingTask(object: "Butterfly", commandPhrase: "a butterfly!", genericDescription: "Draw a colorful insect!", emoji: "🦋"),
        DrawingTask(object: "Cactus", commandPhrase: "a cactus!", genericDescription: "Draw a hurtful plant!", emoji: "🌵"),
        DrawingTask(object: "Cake", commandPhrase: "a cake!", genericDescription: "Draw a dessert!", emoji: "🎂"),
        DrawingTask(object: "Calendar", commandPhrase: "a calendar!", genericDescription: "Draw a time organizer!", emoji: "📆"),
        DrawingTask(object: "Camel", commandPhrase: "a camel!", genericDescription: "Draw a desert animal!", emoji: "🐫"),
        DrawingTask(object: "Camera", commandPhrase: "a camera!", genericDescription: "Draw something with a lens!", emoji: "📸"),
        DrawingTask(object: "Camouflage", commandPhrase: "some camouflage!", genericDescription: "Draw a disguise!", emoji: "🥸"),
        DrawingTask(object: "Campfire", commandPhrase: "a campfire!", genericDescription: "Draw a camping tradition!", emoji: "🔥"),
        DrawingTask(object: "Candle", commandPhrase: "a candle!", genericDescription: "Draw a non-electronic light!", emoji: "🕯"),
        DrawingTask(object: "Cannon", commandPhrase: "a cannon!", genericDescription: "Draw an old-timey weapon!", emoji: "🧨"),
        DrawingTask(object: "Castle", commandPhrase: "a castle!", genericDescription: "Draw a huge house!", emoji: "🏰"),
        DrawingTask(object: "Ceiling Fan", commandPhrase: "a ceiling fan!", genericDescription: "Draw a home coolant!", emoji: "💨"),
        DrawingTask(object: "Cello", commandPhrase: "a cello!", genericDescription: "Draw a classy instrument!", emoji: "🎻"),
        DrawingTask(object: "Cell Phone", commandPhrase: "a cell phone!", genericDescription: "Draw the gadget everyone has!", emoji: "📱"),
        DrawingTask(object: "Chair", commandPhrase: "a chair!", genericDescription: "Draw a butt holder!", emoji: "🪑"),
        DrawingTask(object: "Chandelier", commandPhrase: "a chandelier!", genericDescription: "Draw a fancy light fixture!", emoji: "💡"),
        DrawingTask(object: "Church", commandPhrase: "a church!", genericDescription: "Draw a religious building!", emoji: "⛪️"),
        DrawingTask(object: "Circle", commandPhrase: "a circle!", genericDescription: "Draw a basic shape!", emoji: "🔵"),
        DrawingTask(object: "Clarinet", commandPhrase: "a clarinet!", genericDescription: "Draw a long instrument!", emoji: "🎶"),
        DrawingTask(object: "Cloud", commandPhrase: "a cloud!", genericDescription: "Draw a sky floater!", emoji: "☁️"),
        DrawingTask(object: "Coffee Cup", commandPhrase: "a coffee cup!", genericDescription: "Draw a caffeine container!", emoji: "☕️"),
        DrawingTask(object: "Compass", commandPhrase: "a compass!", genericDescription: "Draw a wayfinder!", emoji: "🧭"),
        DrawingTask(object: "Computer", commandPhrase: "a computer!", genericDescription: "Draw something electronic!", emoji: "🖥"),
        DrawingTask(object: "Cookie", commandPhrase: "a cookie!", genericDescription: "Draw a hard dessert!", emoji: "🍪"),
        DrawingTask(object: "Cooler", commandPhrase: "a cooler!", genericDescription: "Draw a portable coolant!", emoji: "🧊"),
        DrawingTask(object: "Couch", commandPhrase: "a couch!", genericDescription: "Draw some cozy seats!", emoji: "🛋"),
        DrawingTask(object: "Cow", commandPhrase: "a cow!", genericDescription: "Draw a farm animal!", emoji: "🐮"),
        DrawingTask(object: "Crab", commandPhrase: "a crab!", genericDescription: "Draw an orange animal!", emoji: "🦀"),
        DrawingTask(object: "Crayon", commandPhrase: "a crayon!", genericDescription: "Draw a colorful art tool!", emoji: "🖍"),
        DrawingTask(object: "Crocodile", commandPhrase: "a crocodile!", genericDescription: "Draw a green animal!", emoji: "🐊"),
        DrawingTask(object: "Cruise Ship", commandPhrase: "a cruise ship!", genericDescription: "Draw a moving vacation!", emoji: "🛳"),
        DrawingTask(object: "Cup", commandPhrase: "a cup!", genericDescription: "Draw a container!", emoji: "🥤"),
        DrawingTask(object: "Diamond", commandPhrase: "a diamond!", genericDescription: "Draw an expensive gem!", emoji: "💎"),
        DrawingTask(object: "Dishwasher", commandPhrase: "a dishwasher!", genericDescription: "Draw an appliance!", emoji: "🍽"),
        DrawingTask(object: "Diving Board", commandPhrase: "a diving board!", genericDescription: "Draw a pool accessory!", emoji: "🏊"),
        DrawingTask(object: "Dog", commandPhrase: "a dog!", genericDescription: "Draw a popular pet!", emoji: "🐶"),
        DrawingTask(object: "Dolphin", commandPhrase: "a dolphin!", genericDescription: "Draw a smart animal!", emoji: "🐬"),
        DrawingTask(object: "Donut", commandPhrase: "a donut!", genericDescription: "Draw a circular snack!", emoji: "🍩"),
        DrawingTask(object: "Dragon", commandPhrase: "a dragon!", genericDescription: "Draw a mythical beast!", emoji: "🐲"),
        DrawingTask(object: "Dresser", commandPhrase: "a dresser!", genericDescription: "Draw a clothing container!", emoji: "🗄"),
        DrawingTask(object: "Drill", commandPhrase: "a drill!", genericDescription: "Draw a building tool!", emoji: "🔩"),
        DrawingTask(object: "Drums", commandPhrase: "drums!", genericDescription: "Draw some percussion!", emoji: "🥁"),
        DrawingTask(object: "Duck", commandPhrase: "a duck!", genericDescription: "Draw a common animal!", emoji: "🦆"),
        DrawingTask(object: "Dumbbell", commandPhrase: "a dumbbell!", genericDescription: "Draw gym equipment!", emoji: "🏋️"),
        DrawingTask(object: "Ear", commandPhrase: "an ear!", genericDescription: "Draw a body part on the head!", emoji: "👂"),
        DrawingTask(object: "Elbow", commandPhrase: "an elbow!", genericDescription: "Draw a part of the arm!", emoji: "🤳"),
        DrawingTask(object: "Elephant", commandPhrase: "an elephant!", genericDescription: "Draw a unique animal!", emoji: "🐘"),
        DrawingTask(object: "Envelope", commandPhrase: "an envelope!", genericDescription: "Draw a paper container!", emoji: "✉️"),
        DrawingTask(object: "Eraser", commandPhrase: "an eraser!", genericDescription: "Draw a part of a pencil!", emoji: "📝"),
        DrawingTask(object: "Eye", commandPhrase: "an eye!", genericDescription: "Draw a colorful body part!", emoji: "👁"),
        DrawingTask(object: "Eyeglasses", commandPhrase: "some eyeglasses!", genericDescription: "Draw eye accessories!", emoji: "👓"),
        DrawingTask(object: "Face", commandPhrase: "a face!", genericDescription: "Draw an important body area!", emoji: "🙂"),
        DrawingTask(object: "Fan", commandPhrase: "a fan!", genericDescription: "Draw a personal coolant!", emoji: "🌬"),
        DrawingTask(object: "Feather", commandPhrase: "a feather!", genericDescription: "Draw something light!", emoji: "🪶"),
        DrawingTask(object: "Fence", commandPhrase: "a fence!", genericDescription: "Draw a barrier!", emoji: "🤺"),
        DrawingTask(object: "Finger", commandPhrase: "a finger!", genericDescription: "Draw a body part you have lots of!", emoji: "👆"),
        DrawingTask(object: "Fire Hydrant", commandPhrase: "a fire hydrant!", genericDescription: "Draw an emergency water tool!", emoji: "🧯"),
        DrawingTask(object: "Fireplace", commandPhrase: "a fireplace!", genericDescription: "Draw a household hot zone!", emoji: "🪵"),
        DrawingTask(object: "Firetruck", commandPhrase: "a firetruck!", genericDescription: "Draw an emergency vehicle!", emoji: "🚒"),
        DrawingTask(object: "Fish", commandPhrase: "a fish!", genericDescription: "Draw an aquatic animal!", emoji: "🐟"),
        DrawingTask(object: "Flamingo", commandPhrase: "a flamingo!", genericDescription: "Draw a pink animal!", emoji: "🦩"),
        DrawingTask(object: "Flashlight", commandPhrase: "a flashlight!", genericDescription: "Draw an electronic light source!", emoji: "🔦"),
        DrawingTask(object: "Flip Flops", commandPhrase: "some flip flops!", genericDescription: "Draw beach footwear!", emoji: "🩴"),
        DrawingTask(object: "Floor Lamp", commandPhrase: "a floor lamp!", genericDescription: "Draw an indoor light source!", emoji: "🪔"),
        DrawingTask(object: "Flower", commandPhrase: "a flower!", genericDescription: "Draw a common plant!", emoji: "🌸"),
        DrawingTask(object: "Flying Saucer", commandPhrase: "a flying saucer!", genericDescription: "Draw a mythical sky vehicle!", emoji: "🛸"),
        DrawingTask(object: "Foot", commandPhrase: "a foot!", genericDescription: "Draw what you can walk on!", emoji: "🦶"),
        DrawingTask(object: "Fork", commandPhrase: "a fork!", genericDescription: "Draw a utensil!", emoji: "🍴"),
        DrawingTask(object: "Frog", commandPhrase: "a frog!", genericDescription: "Draw a loud animal!", emoji: "🐸"),
        DrawingTask(object: "Frying Pan", commandPhrase: "a frying pan!", genericDescription: "Draw a kitchen item!", emoji: "🍳"),
        DrawingTask(object: "Garden", commandPhrase: "a garden!", genericDescription: "Draw a place with plants!", emoji: "🏡"),
        DrawingTask(object: "Garden Hose", commandPhrase: "a garden hose!", genericDescription: "Draw an outdoor water tool!", emoji: "💦"),
        DrawingTask(object: "Giraffe", commandPhrase: "a giraffe!", genericDescription: "Draw a tall animal!", emoji: "🦒"),
        DrawingTask(object: "Goatee", commandPhrase: "a goatee!", genericDescription: "Draw a kind of facial hair!", emoji: "🧔"),
        DrawingTask(object: "Golf Club", commandPhrase: "a golf club!", genericDescription: "Draw a long sports tool!", emoji: "⛳️"),
        DrawingTask(object: "Grapes", commandPhrase: "some grapes!", genericDescription: "Draw small round fruit!", emoji: "🍇"),
        DrawingTask(object: "Grass", commandPhrase: "some grass!", genericDescription: "Draw a common green plant!", emoji: "🌱"),
        DrawingTask(object: "Guitar", commandPhrase: "a guitar!", genericDescription: "Draw a string instrument!", emoji: "🎸"),
        DrawingTask(object: "Hamburger", commandPhrase: "a hamburger!", genericDescription: "Draw a meat sandwich!", emoji: "🍔"),
        DrawingTask(object: "Hammer", commandPhrase: "a hammer!", genericDescription: "Draw a weapon or building tool!", emoji: "🔨"),
        DrawingTask(object: "Hand", commandPhrase: "a hand!", genericDescription: "Draw what you can type with!", emoji: "✋"),
        DrawingTask(object: "Harp", commandPhrase: "a harp", genericDescription: "Draw an exotic string instrument!", emoji: "🎵"),
        DrawingTask(object: "Hat", commandPhrase: "a hat!", genericDescription: "Draw a head accessory!", emoji: "🎩"),
        DrawingTask(object: "Headphones", commandPhrase: "some headphones!", genericDescription: "Draw a personal music player!", emoji: "🎧"),
        DrawingTask(object: "Hedgehog", commandPhrase: "a hedgehog!", genericDescription: "Draw a fast blue animal!", emoji: "🦔"),
        DrawingTask(object: "Helicopter", commandPhrase: "a helicopter!", genericDescription: "Draw a flying machine!", emoji: "🚁"),
        DrawingTask(object: "Helmet", commandPhrase: "a helmet!", genericDescription: "Draw brain protection!", emoji: "🪖"),
        DrawingTask(object: "Hexagon", commandPhrase: "a hexagon!", genericDescription: "Draw the shape of 6!", emoji: "6️⃣"),
        DrawingTask(object: "Hockey Puck", commandPhrase: "a hockey puck!", genericDescription: "Draw a sports disk!", emoji: "🏒"),
        DrawingTask(object: "Hockey Stick", commandPhrase: "a hockey stick!", genericDescription: "Draw a cold sports stick!", emoji: "🏒"),
        DrawingTask(object: "Horse", commandPhrase: "a horse!", genericDescription: "Draw a racing animal!", emoji: "🐴"),
        DrawingTask(object: "Hospital", commandPhrase: "a hospital!", genericDescription: "Draw a life-saving building!", emoji: "🏥"),
        DrawingTask(object: "Hot Air Balloon", commandPhrase: "a hot air balloon!", genericDescription: "Draw an exotic flying machine!", emoji: "🎈"),
        DrawingTask(object: "Hot Dog", commandPhrase: "a hot dog!", genericDescription: "Draw a horizontal food!", emoji: "🌭"),
        DrawingTask(object: "Hot Tub", commandPhrase: "a hot tub!", genericDescription: "Draw a relaxing water container!", emoji: "🛀"),
        DrawingTask(object: "Hourglass", commandPhrase: "an hourglass!", genericDescription: "Draw an exotic timer!", emoji: "⏳"),
        DrawingTask(object: "House", commandPhrase: "a house!", genericDescription: "Draw a dwelling!", emoji: "🏠"),
        DrawingTask(object: "House Plant", commandPhrase: "a house plant!", genericDescription: "Draw a personal plant!", emoji: "🪴"),
        DrawingTask(object: "Hurricane", commandPhrase: "a hurricane!", genericDescription: "Draw a wind storm!", emoji: "🌀"),
        DrawingTask(object: "Ice Cream", commandPhrase: "some ice cream!", genericDescription: "Draw a tasty cold treat!", emoji: "🍦"),
        DrawingTask(object: "Jacket", commandPhrase: "a jacket!", genericDescription: "Draw some outerwear!", emoji: "🧥"),
        DrawingTask(object: "Jail", commandPhrase: "a jail!", genericDescription: "Draw involuntary housing!", emoji: "🗝"),
        DrawingTask(object: "Kangaroo", commandPhrase: "a kangaroo!", genericDescription: "Draw an animal down under!", emoji: "🦘"),
        DrawingTask(object: "Key", commandPhrase: "a key!", genericDescription: "Draw a unique valuable!", emoji: "🔑"),
        DrawingTask(object: "Keyboard", commandPhrase: "a keyboard!", genericDescription: "Draw how you write online!", emoji: "⌨️"),
        DrawingTask(object: "Knee", commandPhrase: "a knee!", genericDescription: "Draw a part of the leg!", emoji: "🦵"),
        DrawingTask(object: "Knife", commandPhrase: "a knife!", genericDescription: "Draw a weapon and a kitchen tool!", emoji: "🔪"),
        DrawingTask(object: "Ladder", commandPhrase: "a ladder!", genericDescription: "Draw a climbing tool!", emoji: "🪜"),
        DrawingTask(object: "Lantern", commandPhrase: "a lantern!", genericDescription: "Draw a fancy lighting method!", emoji: "🏮"),
        DrawingTask(object: "Laptop", commandPhrase: "a laptop!", genericDescription: "Draw a portable screen!", emoji: "💻"),
        DrawingTask(object: "Leaf", commandPhrase: "a leaf!", genericDescription: "Draw a plant part!", emoji: "🍃"),
        DrawingTask(object: "Leg", commandPhrase: "a leg!", genericDescription: "Draw how you can walk!", emoji: "🦵"),
        DrawingTask(object: "Light Bulb", commandPhrase: "a light bulb!", genericDescription: "Draw a part of a lamp!", emoji: "💡"),
        DrawingTask(object: "Lighter", commandPhrase: "a lighter!", genericDescription: "Draw a firestarter!", emoji: "🔥"),
        DrawingTask(object: "Lighthouse", commandPhrase: "a lighthouse!", genericDescription: "Draw a guidance tower!", emoji: "🗼"),
        DrawingTask(object: "Lightning", commandPhrase: "some lightning!", genericDescription: "Draw a product of a storm!", emoji: "⚡️"),
        DrawingTask(object: "Line", commandPhrase: "a line!", genericDescription: "Draw where you wait!", emoji: "📈"),
        DrawingTask(object: "Lion", commandPhrase: "a lion!", genericDescription: "Draw a hairy beast!", emoji: "🦁"),
        DrawingTask(object: "Lipstick", commandPhrase: "some lipstick!", genericDescription: "Draw a kind of makeup!", emoji: "💄"),
        DrawingTask(object: "Lobster", commandPhrase: "a lobster!", genericDescription: "Draw a common seafood type!", emoji: "🦞"),
        DrawingTask(object: "Lollipop", commandPhrase: "a lollipop!", genericDescription: "Draw a round candy!", emoji: "🍭"),
        DrawingTask(object: "Mailbox", commandPhrase: "a mailbox!", genericDescription: "Draw a box with an address!", emoji: "📫"),
        DrawingTask(object: "Map", commandPhrase: "a map!", genericDescription: "Draw a guiding paper!", emoji: "🗺"),
        DrawingTask(object: "Marker", commandPhrase: "a marker!", genericDescription: "Draw a colorful art tool!", emoji: "🖊"),
        DrawingTask(object: "Matches", commandPhrase: "some matches!", genericDescription: "Draw old-fashioned firestarters", emoji: "🔥"),
        DrawingTask(object: "Megaphone", commandPhrase: "a megaphone!", genericDescription: "Draw a voice amplifier!", emoji: "📣"),
        DrawingTask(object: "Mermaid", commandPhrase: "a mermaid!", genericDescription: "Draw a mythical sea creature!", emoji: "🧜‍♀️"),
        DrawingTask(object: "Microphone", commandPhrase: "a microphone!", genericDescription: "Draw a small voice amplifier!", emoji: "🎤"),
        DrawingTask(object: "Microwave", commandPhrase: "a microwave!", genericDescription: "Draw a food heater!", emoji: "⏲"),
        DrawingTask(object: "Monkey", commandPhrase: "a monkey!", genericDescription: "Draw a close relative!", emoji: "🐵"),
        DrawingTask(object: "Moon", commandPhrase: "the Moon!", genericDescription: "Draw a close neighbor!", emoji: "🌙"),
        DrawingTask(object: "Mosquito", commandPhrase: "a mosquito!", genericDescription: "Draw a vampiric pest!", emoji: "🦟"),
        DrawingTask(object: "Motorbike", commandPhrase: "a motorbike!", genericDescription: "Draw a super cool bike!", emoji: "🏍"),
        DrawingTask(object: "Mountain", commandPhrase: "a mountain", genericDescription: "Draw a tall part of nature!", emoji: "🏔"),
        DrawingTask(object: "Mouse", commandPhrase: "a mouse!", genericDescription: "Draw something that likes cheese!", emoji: "🐁"),
        DrawingTask(object: "Moustache", commandPhrase: "a moustache!", genericDescription: "Draw a kind of facial hair!", emoji: "🧑‍🦳"),
        DrawingTask(object: "Mouth", commandPhrase: "a mouth!", genericDescription: "Draw how you speak!", emoji: "👄"),
        DrawingTask(object: "Mug", commandPhrase: "a mug!", genericDescription: "Draw a cofee container!", emoji: "🍺"),
        DrawingTask(object: "Mushroom", commandPhrase: "a mushroom!", genericDescription: "Draw a fun guy!", emoji: "🍄"),
        DrawingTask(object: "Nail", commandPhrase: "a nail!", genericDescription: "Draw something sharp!", emoji: "💅"),
        DrawingTask(object: "Necklace", commandPhrase: "a necklace!", genericDescription: "Draw a neck accessory!", emoji: "🧣"),
        DrawingTask(object: "Nose", commandPhrase: "a nose!", genericDescription: "Draw how you smell!", emoji: "👃"),
        DrawingTask(object: "Ocean", commandPhrase: "the ocean!", genericDescription: "Draw most of the planet!", emoji: "🌊"),
        DrawingTask(object: "Octagon", commandPhrase: "an octagon!", genericDescription: "Draw a shape with 6 sides!", emoji: "🛑"),
        DrawingTask(object: "Octopus", commandPhrase: "an octopus!", genericDescription: "Draw a sea creature with lots of arms!", emoji: "🐙"),
        DrawingTask(object: "Onion", commandPhrase: "an onion!", genericDescription: "Draw something that causes tears!", emoji: "🧅"),
        DrawingTask(object: "Oven", commandPhrase: "an oven!", genericDescription: "Draw something really hot!", emoji: "♨️"),
        DrawingTask(object: "Owl", commandPhrase: "an owl!", genericDescription: "Draw a nocturnal animal!", emoji: "🦉"),
        DrawingTask(object: "Paintbrush", commandPhrase: "a paintbrush!", genericDescription: "Draw a common art tool!", emoji: "🖌"),
        DrawingTask(object: "Paint Can", commandPhrase: "a paint can!", genericDescription: "Draw an art tool storage device!", emoji: "🎨"),
        DrawingTask(object: "Palm Tree", commandPhrase: "a palm tree!", genericDescription: "Draw a tropical plant!", emoji: "🌴"),
        DrawingTask(object: "Panda", commandPhrase: "a panda!", genericDescription: "Draw a black and white animal!", emoji: "🐼"),
        DrawingTask(object: "Pants", commandPhrase: "a pair of pants!", genericDescription: "Draw a leg accessory!", emoji: "👖"),
        DrawingTask(object: "Paper Clip", commandPhrase: "a paper clip!", genericDescription: "Draw a very small office essential!", emoji: "📎"),
        DrawingTask(object: "Parachute", commandPhrase: "a parachute!", genericDescription: "Draw a floating device!", emoji: "🪂"),
        DrawingTask(object: "Parrot", commandPhrase: "a parrot!", genericDescription: "Draw a talking animal!", emoji: "🦜"),
        DrawingTask(object: "Passport", commandPhrase: "a passport!", genericDescription: "Draw a travel essential!", emoji: "🛂"),
        DrawingTask(object: "Peanut", commandPhrase: "a peanut!", genericDescription: "Draw a common allergen!", emoji: "🥜"),
        DrawingTask(object: "Pear", commandPhrase: "a pear!", genericDescription: "Draw a green fruit!", emoji: "🍐"),
        DrawingTask(object: "Peas", commandPhrase: "some peas!", genericDescription: "Draw some small green veggies!", emoji: "🟢"),
        DrawingTask(object: "Pencil", commandPhrase: "a pencil!", genericDescription: "Draw a school essential!", emoji: "✏️"),
        DrawingTask(object: "Penguin", commandPhrase: "a penguin!", genericDescription: "Draw a chilly animal!", emoji: "🐧"),
        DrawingTask(object: "Piano", commandPhrase: "a piano!", genericDescription: "Draw a common instrument!", emoji: "🎹"),
        DrawingTask(object: "Pickup Truck", commandPhrase: "a pickup truck!", genericDescription: "Draw a kind of truck!", emoji: "🛻"),
        DrawingTask(object: "Picture Frame", commandPhrase: "a picture frame!", genericDescription: "Draw a photo holder!", emoji: "🖼"),
        DrawingTask(object: "Pig", commandPhrase: "a pig!", genericDescription: "Draw a pink animal!", emoji: "🐷"),
        DrawingTask(object: "Pillow", commandPhrase: "a pillow!", genericDescription: "Draw a soft headrest!", emoji: "🛌"),
        DrawingTask(object: "Pineapple", commandPhrase: "a pineapple!", genericDescription: "Draw a yellow fruit!", emoji: "🍍"),
        DrawingTask(object: "Pizza", commandPhrase: "a pizza!", genericDescription: "Draw a food with slices!", emoji: "🍕"),
        DrawingTask(object: "Pliers", commandPhrase: "some pliers!", genericDescription: "Draw a pulling tool!", emoji: "🔧"),
        DrawingTask(object: "Police Car", commandPhrase: "a police car!", genericDescription: "Draw a vehicle with sirens!", emoji: "🚔"),
        DrawingTask(object: "Pond", commandPhrase: "a pond!", genericDescription: "Draw a smaller lake!", emoji: "💧"),
        DrawingTask(object: "Popsicle", commandPhrase: "a popsicle!", genericDescription: "Draw a colorful cold treat!", emoji: "🍭"),
        DrawingTask(object: "Postcard", commandPhrase: "a postcard!", genericDescription: "Draw vacation mail!", emoji: "🌅"),
        DrawingTask(object: "Potato", commandPhrase: "a potato!", genericDescription: "Draw what french fries are made of!", emoji: "🥔"),
        DrawingTask(object: "Power Outlet", commandPhrase: "a power outlet!", genericDescription: "Draw where to plug in!", emoji: "🔌"),
        DrawingTask(object: "Purse", commandPhrase: "a purse!", genericDescription: "Draw portable storage!", emoji: "👜"),
        DrawingTask(object: "Rabbit", commandPhrase: "a rabbit!", genericDescription: "Draw a magic animal!", emoji: "🐰"),
        DrawingTask(object: "Raccoon", commandPhrase: "a raccoon!", genericDescription: "Draw a trashy animal!", emoji: "🦝"),
        DrawingTask(object: "Radio", commandPhrase: "a radio!", genericDescription: "Draw a speaker with stations!", emoji: "📻"),
        DrawingTask(object: "Rain", commandPhrase: "rain!", genericDescription: "Draw a product of a storm!", emoji: "🌧"),
        DrawingTask(object: "Rainbow", commandPhrase: "a rainbow!", genericDescription: "Draw all the colors!", emoji: "🌈"),
        DrawingTask(object: "Rake", commandPhrase: "a rake!", genericDescription: "Draw a leaf manager!", emoji: "🍂"),
        DrawingTask(object: "Remote Control", commandPhrase: "a remote control!", genericDescription: "Draw a TV manager!", emoji: "🕹"),
        DrawingTask(object: "Rhinoceros", commandPhrase: "a rhinoceros!", genericDescription: "Draw an animal with a horn!", emoji: "🦏"),
        DrawingTask(object: "Rifle", commandPhrase: "a rifle!", genericDescription: "Draw a weapon!", emoji: "🔫"),
        DrawingTask(object: "River", commandPhrase: "a river!", genericDescription: "Draw moving water!", emoji: "🏞"),
        DrawingTask(object: "Roller Coaster", commandPhrase: "a roller coaster!", genericDescription: "Draw a fast ride!", emoji: "🎢"),
        DrawingTask(object: "Rollerskates", commandPhrase: "some rollerskates!", genericDescription: "Draw mobile footwear!", emoji: "🛼"),
        DrawingTask(object: "Sailboat", commandPhrase: "a sailboat!", genericDescription: "Draw an old-style boat!", emoji: "⛵️"),
        DrawingTask(object: "Sandwich", commandPhrase: "a sandwich!", genericDescription: "Draw a customizable food!", emoji: "🥪"),
        DrawingTask(object: "Saw", commandPhrase: "a saw!", genericDescription: "Draw a sharp tool!", emoji: "🪚"),
        DrawingTask(object: "Saxophone", commandPhrase: "a saxophone!", genericDescription: "Draw a sexy instrument!", emoji: "🎷"),
        DrawingTask(object: "School Bus", commandPhrase: "a school bus!", genericDescription: "Draw a yellow vehicle!", emoji: "🚌"),
        DrawingTask(object: "Scissors", commandPhrase: "some scissors!", genericDescription: "Draw a household sharp tool!", emoji: "✂️"),
        DrawingTask(object: "Scorpion", commandPhrase: "a scorpion", genericDescription: "Draw a sharp animal!", emoji: "🦂"),
        DrawingTask(object: "Screwdriver", commandPhrase: "a screwdriver!", genericDescription: "Draw an essential household tool!", emoji: "🪛"),
        DrawingTask(object: "Sea Turtle", commandPhrase: "a sea turtle!", genericDescription: "Draw a green aquatic animal!", emoji: "🐢"),
        DrawingTask(object: "See Saw", commandPhrase: "a see saw!", genericDescription: "Draw a playground bar!", emoji: "⚖️"),
        DrawingTask(object: "Shark", commandPhrase: "a shark!", genericDescription: "Draw a scary underwater animal!", emoji: "🦈"),
        DrawingTask(object: "Sheep", commandPhrase: "a sheep!", genericDescription: "Draw a soft farm animal!", emoji: "🐑"),
        DrawingTask(object: "Shoe", commandPhrase: "a shoe!", genericDescription: "Draw a foot accessory!", emoji: "👞"),
        DrawingTask(object: "Shorts", commandPhrase: "some shorts!", genericDescription: "Draw a leg accessory!", emoji: "🩳"),
        DrawingTask(object: "Shovel", commandPhrase: "a shovel!", genericDescription: "Draw a digging tool!", emoji: "🕳"),
        DrawingTask(object: "Sink", commandPhrase: "a sink!", genericDescription: "Draw a wet place from the bathroom!", emoji: "🚰"),
        DrawingTask(object: "Skateboard", commandPhrase: "a skateboard!", genericDescription: "Draw a personal rolling device!", emoji: "🛹"),
        DrawingTask(object: "Sleeping Bag", commandPhrase: "a sleeping bag!", genericDescription: "Draw a portable bed!", emoji: "💤"),
        DrawingTask(object: "Skull", commandPhrase: "a skull!", genericDescription: "Draw part of a skeleton!", emoji: "💀"),
        DrawingTask(object: "Skyscraper", commandPhrase: "a skyscraper!", genericDescription: "Draw a tall place!", emoji: "🏙"),
        DrawingTask(object: "Smiley Face", commandPhrase: "a smiley face!", genericDescription: "Draw a happy emoji!", emoji: "😄"),
        DrawingTask(object: "Snail", commandPhrase: "a snail!", genericDescription: "Draw a slow animal!", emoji: "🐌"),
        DrawingTask(object: "Snake", commandPhrase: "a snake!", genericDescription: "Draw a long animal!", emoji: "🐍"),
        DrawingTask(object: "Snorkel", commandPhrase: "a snorkel!", genericDescription: "Draw underwater eyewear!", emoji: "🤿"),
        DrawingTask(object: "Snowflake", commandPhrase: "a snowflake!", genericDescription: "Draw something cold and unique!", emoji: "❄️"),
        DrawingTask(object: "Snowman", commandPhrase: "a snowman!", genericDescription: "Draw someone cold!", emoji: "☃️"),
        DrawingTask(object: "Soccer Ball", commandPhrase: "a soccer ball!", genericDescription: "Draw a black and white sports object!", emoji: "⚽️"),
        DrawingTask(object: "Sock", commandPhrase: "a sock!", genericDescription: "Draw a foot accessory!", emoji: "🧦"),
        DrawingTask(object: "Speedboat", commandPhrase: "a speedboat!", genericDescription: "Draw a fast kind of boat!", emoji: "🚤"),
        DrawingTask(object: "Spider", commandPhrase: "a spider!", genericDescription: "Draw a scary insect!", emoji: "🕷"),
        DrawingTask(object: "Spoon", commandPhrase: "a spoon!", genericDescription: "Draw a kitchen utensil!", emoji: "🥄"),
        DrawingTask(object: "Spreadsheet", commandPhrase: "a spreadsheet!", genericDescription: "Draw a fancy kind of table!", emoji: "📊"),
        DrawingTask(object: "Square", commandPhrase: "a square!", genericDescription: "Draw a very basic shape!", emoji: "🟦"),
        DrawingTask(object: "Squiggle", commandPhrase: "a squiggle!", genericDescription: "Draw a curvy line!", emoji: "🌀"),
        DrawingTask(object: "Stairs", commandPhrase: "some stairs!", genericDescription: "Draw how to ascend somewhere!", emoji: "↗️"),
        DrawingTask(object: "Star", commandPhrase: "a star!", genericDescription: "Draw something really, really, really hot!", emoji: "⭐️"),
        DrawingTask(object: "Steak", commandPhrase: "a steak!", genericDescription: "Draw what a cow becomes!", emoji: "🥩"),
        DrawingTask(object: "Stereo", commandPhrase: "a stereo!", genericDescription: "Draw a fancy speaker!", emoji: "🔊"),
        DrawingTask(object: "Stethoscope", commandPhrase: "a stethoscope!", genericDescription: "Draw a doctor's headphones!", emoji: "🩺"),
        DrawingTask(object: "Stitches", commandPhrase: "some stitches!", genericDescription: "Draw advanced bandages!", emoji: "🧵"),
        DrawingTask(object: "Stop Sign", commandPhrase: "a stop sign!", genericDescription: "Draw a red octagon!", emoji: "🛑"),
        DrawingTask(object: "Stove", commandPhrase: "a stove!", genericDescription: "Draw something you shouldn't leave on!", emoji: "🎛"),
        DrawingTask(object: "Strawberry", commandPhrase: "a strawberry!", genericDescription: "Draw a small red fruit!", emoji: "🍓"),
        DrawingTask(object: "Streetlight", commandPhrase: "a streetlight!", genericDescription: "Draw an outdoor light source!", emoji: "💡"),
        DrawingTask(object: "String Bean", commandPhrase: "a string bean!", genericDescription: "Draw a unique kind of bean!", emoji: "🫘"),
        DrawingTask(object: "Submarine", commandPhrase: "a submarine!", genericDescription: "Draw an underwater car!", emoji: "🫧"),
        DrawingTask(object: "Suitcase", commandPhrase: "a suitcase!", genericDescription: "Draw a travel companion!", emoji: "🧳"),
        DrawingTask(object: "Sun", commandPhrase: "the Sun!", genericDescription: "Draw our biggest light source!", emoji: "☀️"),
        DrawingTask(object: "Swan", commandPhrase: "a swan!", genericDescription: "Draw a majestic white bird!", emoji: "🦢"),
        DrawingTask(object: "Sweater", commandPhrase: "a sweater!", genericDescription: "Draw a cozy shirt!", emoji: "👕"),
        DrawingTask(object: "Swing Set", commandPhrase: "a swing set!", genericDescription: "Draw an essential playground installation!", emoji: "↔️"),
        DrawingTask(object: "Sword", commandPhrase: "a sword!", genericDescription: "Draw a classic hero weapon!", emoji: "⚔️"),
        DrawingTask(object: "Syringe", commandPhrase: "a syringe!", genericDescription: "Draw a medicine delivery tool!", emoji: "💉"),
        DrawingTask(object: "Table", commandPhrase: "a table!", genericDescription: "Draw something for placing upon!", emoji: "🍱"),
        DrawingTask(object: "Teapot", commandPhrase: "a teapot!", genericDescription: "Draw a fancy liquid storage device!", emoji: "🫖"),
        DrawingTask(object: "Teddy-Bear", commandPhrase: "a teddy-bear!", genericDescription: "Draw a cuddly bedtime friend!", emoji: "🧸"),
        DrawingTask(object: "Telephone", commandPhrase: "a telephone!", genericDescription: "Draw how to chat from afar!", emoji: "☎️"),
        DrawingTask(object: "Television", commandPhrase: "a television!", genericDescription: "Draw how to see from afar!", emoji: "📺"),
        DrawingTask(object: "Tennis Racquet", commandPhrase: "a tennis racquet!", genericDescription: "Draw a ball hitter!", emoji: "🏓"),
        DrawingTask(object: "Tent", commandPhrase: "a tent!", genericDescription: "Draw a portable house!", emoji: "🏕"),
        DrawingTask(object: "Tiger", commandPhrase: "a tiger!", genericDescription: "Draw a big cat!", emoji: "🐅"),
        DrawingTask(object: "Toaster", commandPhrase: "a toaster!", genericDescription: "Draw a kitchen item with levers!", emoji: "🍞"),
        DrawingTask(object: "Toe", commandPhrase: "a toe!", genericDescription: "Draw a feature of feet!", emoji: "🦶"),
        DrawingTask(object: "Toilet", commandPhrase: "a toilet!", genericDescription: "Draw a very private place!", emoji: "🚽"),
        DrawingTask(object: "Tooth", commandPhrase: "a tooth!", genericDescription: "Draw what you brush!", emoji: "🦷"),
        DrawingTask(object: "Toothbrush", commandPhrase: "a toothbrush!", genericDescription: "Draw a brushing stick!", emoji: "🪥"),
        DrawingTask(object: "Tornado", commandPhrase: "a tornado!", genericDescription: "Draw swirling winds!", emoji: "🌪"),
        DrawingTask(object: "Tractor", commandPhrase: "a tractor!", genericDescription: "Draw a classic farm vehicle!", emoji: "🚜"),
        DrawingTask(object: "Toothpaste", commandPhrase: "some toothpaste!", genericDescription: "Draw what you brush with!", emoji: "🧴"),
        DrawingTask(object: "Traffic Light", commandPhrase: "a traffic light!", genericDescription: "Draw an electronic sign!", emoji: "🚦"),
        DrawingTask(object: "Train", commandPhrase: "a train!", genericDescription: "Draw a group of moving cars!", emoji: "🚃"),
        DrawingTask(object: "Tree", commandPhrase: "a tree!", genericDescription: "Draw a tall plant!", emoji: "🌲"),
        DrawingTask(object: "Triangle", commandPhrase: "a triangle!", genericDescription: "Draw a strong basic shape!", emoji: "🔺"),
        DrawingTask(object: "Trombone", commandPhrase: "a trombone!", genericDescription: "Draw a sliding instrument!", emoji: "🎶"),
        DrawingTask(object: "Truck", commandPhrase: "a truck!", genericDescription: "Draw a big car!", emoji: "🚚"),
        DrawingTask(object: "Trumpet", commandPhrase: "a trumpet!", genericDescription: "Draw an instrument with valves!", emoji: "🎺"),
        DrawingTask(object: "T-Shirt", commandPhrase: "a T-Shirt!", genericDescription: "Draw classic top wear!", emoji: "👕"),
        DrawingTask(object: "Umbrella", commandPhrase: "an umbrella!", genericDescription: "Draw a moisture negator!", emoji: "☂️"),
        DrawingTask(object: "Underwear", commandPhrase: "a pair of underwear!", genericDescription: "Draw what's under there!", emoji: "🩲"),
        DrawingTask(object: "Van", commandPhrase: "a van!", genericDescription: "Draw a wide car!", emoji: "🚐"),
        DrawingTask(object: "Vase", commandPhrase: "a vase!", genericDescription: "Draw a fancy pot!", emoji: "🏺"),
        DrawingTask(object: "Violin", commandPhrase: "a violin!", genericDescription: "Draw a classic orchestra instrument!", emoji: "🎻"),
        DrawingTask(object: "Washing Machine", commandPhrase: "a washing machine!", genericDescription: "Draw a clothing appliance!", emoji: "🧼"),
        DrawingTask(object: "Watermelon", commandPhrase: "a watermelon!", genericDescription: "Draw a big fruit with seeds!", emoji: "🍉"),
        DrawingTask(object: "Waterslide", commandPhrase: "a waterslide!", genericDescription: "Draw a waterpark staple!", emoji: "🛝"),
        DrawingTask(object: "Whale", commandPhrase: "a whale!", genericDescription: "Draw the biggest animal!", emoji: "🐋"),
        DrawingTask(object: "Wheel", commandPhrase: "a wheel!", genericDescription: "Draw what makes cars go!", emoji: "🛞"),
        DrawingTask(object: "Windmill", commandPhrase: "a windmill!", genericDescription: "Draw clean energy generation!", emoji: "💨"),
        DrawingTask(object: "Wine Bottle", commandPhrase: "a wine bottle!", genericDescription: "Draw a container for specific alcohol!", emoji: "🍾"),
        DrawingTask(object: "Wine Glass", commandPhrase: "a wine glass!", genericDescription: "Draw a fancy container for alcohol!", emoji: "🍷"),
        DrawingTask(object: "Wristwatch", commandPhrase: "a wristwatch!", genericDescription: "Draw a portable clock!", emoji: "⌚️"),
        DrawingTask(object: "Yoga", commandPhrase: "some yoga!", genericDescription: "Draw a flexible pose!", emoji: "🧘"),
        DrawingTask(object: "Zebra", commandPhrase: "a zebra!", genericDescription: "Draw a striped animal!", emoji: "🦓"),
        DrawingTask(object: "Zigzag", commandPhrase: "a zigzag!", genericDescription: "Draw a funky line!", emoji: "〽️"),
        DrawingTask(object: "Bird", commandPhrase: "a bird!", genericDescription: "Draw something that flies!", emoji: "🕊"),
        DrawingTask(object: "Bowtie", commandPhrase: "a bowtie!", genericDescription: "Draw a fancy accessory!", emoji: "🎀"),
        DrawingTask(object: "Broom", commandPhrase: "a broom!", genericDescription: "Draw something that cleans!", emoji: "🧹"),
        DrawingTask(object: "Calculator", commandPhrase: "a calculator!", genericDescription: "Draw a common math tool!", emoji: "🧮"),
        DrawingTask(object: "Cat", commandPhrase: "a cat!", genericDescription: "Draw a common pet!", emoji: "😺"),
        DrawingTask(object: "Crown", commandPhrase: "a crown!", genericDescription: "Draw a piece of expensive headwear!", emoji: "👑"),
        DrawingTask(object: "Clock", commandPhrase: "a clock!", genericDescription: "Draw something round with hands!", emoji: "🕓"),
        DrawingTask(object: "Door", commandPhrase: "a door!", genericDescription: "Draw something that opens!", emoji: "🚪")
    ]
    
}
