//
//  Task.swift
//  
//
//  Created by Ethan Marshall on 4/7/22.
//

import Foundation
import CoreML

/// In the context of a game, the action the player must take to score points.
struct Task {
    
    // Variables
    /// The action the player must perform during a game.
    var category: TaskCategory
    /// The specific object the user must perform the action for during a game.
    var object: String
    /// The English phrase that should follow this task's type's verb.
    var commandPhrase: String
    /// A generic description of the task's object for use in Clued In mode.
    var genericDescription: String
    /// The Core ML model trained to assign scores to object task attempts.
    var judgeModel: MLModel = MLModel()
    
    // Computed Properties
    /// An English phrase prompting the user to complete the task.
    var commandPrompt: String {
        var answer = ""
        switch category {
        case .drawing:
            answer += "Draw "
        case .speech:
            answer += "Say "
        case .handPoses:
            answer += "Make "
        }
        answer += commandPhrase
        return answer
    }
    
    // Enumerations
    /// The possible categories of tasks: drawing, speech, and hand poses.
    enum TaskCategory {
        case drawing
        case speech
        case handPoses
    }
    
    // Included App Data
    /// The list of all possible tasks for use in games.
    static var taskList: [Task] = [
        Task(category: .drawing, object: "Aircraft Carrier", commandPhrase: "an aircraft carrier!", genericDescription: "Draw something that carries planes!"),
        Task(category: .drawing, object: "Airplane", commandPhrase: "an airplane!", genericDescription: "Draw something that flies!"),
        Task(category: .drawing, object: "Alarm Clock", commandPhrase: "an alarm clock!", genericDescription: "Draw something thst rings!"),
        Task(category: .drawing, object: "Ambulance", commandPhrase: "an ambulance", genericDescription: "Draw something with sirens!"),
        Task(category: .drawing, object: "Angel", commandPhrase: "an angel!", genericDescription: "Draw something with a halo!"),
        Task(category: .drawing, object: "Animal Migration", commandPhrase: "an animal migration", genericDescription: "Draw a movement of animals!"),
        Task(category: .drawing, object: "Ant", commandPhrase: "an ant!", genericDescription: "Draw a small insect!"),
        Task(category: .drawing, object: "Anvil", commandPhrase: "an anvil!", genericDescription: "Draw a heavy steel tool!"),
        Task(category: .drawing, object: "Apple", commandPhrase: "an apple!", genericDescription: "Draw something round and edible!"),
        Task(category: .drawing, object: "Arm", commandPhrase: "an arm!", genericDescription: "Draw a body part!"),
        Task(category: .drawing, object: "Asparagus", commandPhrase: "an asparagus", genericDescription: "Draw a green veggie!"),
        Task(category: .drawing, object: "Axe", commandPhrase: "an axe!", genericDescription: "Draw something that chops!"),
        Task(category: .drawing, object: "Backpack", commandPhrase: "a backpack!", genericDescription: "Draw a strapped container!"),
        Task(category: .drawing, object: "Banana", commandPhrase: "a banana!", genericDescription: "Draw a yellow food!"),
        Task(category: .drawing, object: "Bandage", commandPhrase: "a bandage!", genericDescription: "Draw a head accessory!"),
        Task(category: .drawing, object: "Barn", commandPhrase: "a barn!", genericDescription: "Draw a farm building!"),
        Task(category: .drawing, object: "Baseball", commandPhrase: "a baseball!", genericDescription: "Draw a sports ball!"),
        Task(category: .drawing, object: "Baseball Bat", commandPhrase: "a baseball bat!", genericDescription: "Draw a long sports instrument!"),
        Task(category: .drawing, object: "Basket", commandPhrase: "a basket!", genericDescription: "Draw a carrier of objects!"),
        Task(category: .drawing, object: "Basketball", commandPhrase: "a basketball!", genericDescription: "Draw a sports ball!"),
        Task(category: .drawing, object: "Bat", commandPhrase: "a bat!", genericDescription: "Draw a long stick-like object!"),
        Task(category: .drawing, object: "Bathtub", commandPhrase: "a bathtub!", genericDescription: "Draw something from the bathroom!"),
        Task(category: .drawing, object: "Beach", commandPhrase: "a beach!", genericDescription: "Draw a vacation destination!"),
        Task(category: .drawing, object: "Bear", commandPhrase: "a bear!", genericDescription: "Draw a scary animal!"),
        Task(category: .drawing, object: "Beard", commandPhrase: "a beard!", genericDescription: "Draw facial hair!"),
        Task(category: .drawing, object: "Bed", commandPhrase: "a bed!", genericDescription: "Draw a sleeping spot!"),
        Task(category: .drawing, object: "Bee", commandPhrase: "a bee!", genericDescription: "Draw a hurtful insect!"),
        Task(category: .drawing, object: "Belt", commandPhrase: "a belt!", genericDescription: "Draw a pants accessory!"),
        Task(category: .drawing, object: "Bench", commandPhrase: "a bench!", genericDescription: "Draw a place to sit!"),
        Task(category: .drawing, object: "Bicycle", commandPhrase: "bicycle", genericDescription: "Draw a mode of transportation!"),
        Task(category: .drawing, object: "Binoculars", commandPhrase: "a pair of binoculars!", genericDescription: "Draw vision enhancers!"),
        Task(category: .drawing, object: "Birthday Cake", commandPhrase: "a birthday cake!", genericDescription: "Draw a special dessert!"),
        Task(category: .drawing, object: "Blackberry", commandPhrase: "a blackberry!", genericDescription: "Draw a kind of phone!"),
        Task(category: .drawing, object: "Blueberry", commandPhrase: "a blueberry!", genericDescription: "Draw a small fruit!"),
        Task(category: .drawing, object: "Book", commandPhrase: "a book!", genericDescription: "Draw a vessel for information!"),
        Task(category: .drawing, object: "Boomerang", commandPhrase: "a boomerang!", genericDescription: "Draw something that always comes back!"),
        Task(category: .drawing, object: "Bottlecap", commandPhrase: "a bottlecap!", genericDescription: "Draw a drink topper!"),
        Task(category: .drawing, object: "Bracelet", commandPhrase: "a bracelet!", genericDescription: "Draw a wrist accessory!"),
        Task(category: .drawing, object: "Brain", commandPhrase: "a brain!", genericDescription: "Draw a hidden body part!"),
        Task(category: .drawing, object: "Bread", commandPhrase: "a piece of bread!", genericDescription: "Draw a carbohydrate snack!"),
        Task(category: .drawing, object: "Bridge", commandPhrase: "a bridge!", genericDescription: "Draw a river crossing!"),
        Task(category: .drawing, object: "Broccoli", commandPhrase: "a piece of broccoli!", genericDescription: "Draw a green, leafy veggie!"),
        Task(category: .drawing, object: "Bucket", commandPhrase: "a bucket!", genericDescription: "Draw a metal container!"),
        Task(category: .drawing, object: "Bulldozer", commandPhrase: "a bulldozer!", genericDescription: "Draw construction equipment!"),
        Task(category: .drawing, object: "Bus", commandPhrase: "a bus!", genericDescription: "Draw a group transportation mode!"),
        Task(category: .drawing, object: "Bush", commandPhrase: "a bush!", genericDescription: "Draw a decorative plant!"),
        Task(category: .drawing, object: "Butterfly", commandPhrase: "a butterfly!", genericDescription: "Draw a colorful insect!"),
        Task(category: .drawing, object: "Cactus", commandPhrase: "a cactus!", genericDescription: "Draw a hurtful plant!"),
        Task(category: .drawing, object: "Cake", commandPhrase: "a cake!", genericDescription: "Draw a dessert!"),
        Task(category: .drawing, object: "Calendar", commandPhrase: "a calendar!", genericDescription: "Draw a time organizer!"),
        Task(category: .drawing, object: "Camel", commandPhrase: "a camel!", genericDescription: "Draw a desert animal!"),
        Task(category: .drawing, object: "Camera", commandPhrase: "a camera!", genericDescription: "Draw something with a lens!"),
        Task(category: .drawing, object: "Camouflage", commandPhrase: "some camouflage!", genericDescription: "Draw a disguise!"),
        Task(category: .drawing, object: "Campfire", commandPhrase: "a campfire!", genericDescription: "Draw a camping tradition!"),
        Task(category: .drawing, object: "Candle", commandPhrase: "a candle!", genericDescription: "Draw a non-electronic light!"),
        Task(category: .drawing, object: "Cannon", commandPhrase: "a cannon!", genericDescription: "Draw an old-timey weapon!"),
        Task(category: .drawing, object: "Castle", commandPhrase: "a castle!", genericDescription: "Draw a huge house!"),
        Task(category: .drawing, object: "Ceiling Fan", commandPhrase: "a ceiling fan!", genericDescription: "Draw a home coolant!"),
        Task(category: .drawing, object: "Cello", commandPhrase: "a cello!", genericDescription: "Draw a classy instrument!"),
        Task(category: .drawing, object: "Cell Phone", commandPhrase: "a cell phone!", genericDescription: "Draw the gadget everyone has!"),
        Task(category: .drawing, object: "Chair", commandPhrase: "a chair!", genericDescription: "Draw a butt holder!"),
        Task(category: .drawing, object: "Chandelier", commandPhrase: "a chandelier!", genericDescription: "Draw a fancy light fixture!"),
        Task(category: .drawing, object: "Church", commandPhrase: "a church!", genericDescription: "Draw a religious building!"),
        Task(category: .drawing, object: "Circle", commandPhrase: "a circle!", genericDescription: "Draw a basic shape!"),
        Task(category: .drawing, object: "Clarinet", commandPhrase: "a clarinet!", genericDescription: "Draw a long instrument!"),
        Task(category: .drawing, object: "Cloud", commandPhrase: "a cloud!", genericDescription: "Draw a sky floater!"),
        Task(category: .drawing, object: "Coffee Cup", commandPhrase: "a coffee cup!", genericDescription: "Draw a caffeine container!"),
        Task(category: .drawing, object: "Compass", commandPhrase: "a compass!", genericDescription: "Draw a wayfinder!"),
        Task(category: .drawing, object: "Computer", commandPhrase: "a computer!", genericDescription: "Draw something electronic!"),
        Task(category: .drawing, object: "Cookie", commandPhrase: "a cookie!", genericDescription: "Draw a hard dessert!"),
        Task(category: .drawing, object: "Cooler", commandPhrase: "a cooler!", genericDescription: "Draw a portable coolant!"),
        Task(category: .drawing, object: "Couch", commandPhrase: "a couch!", genericDescription: "Draw some cozy seats!"),
        Task(category: .drawing, object: "Cow", commandPhrase: "a cow!", genericDescription: "Draw a farm animal!"),
        Task(category: .drawing, object: "Crab", commandPhrase: "a crab!", genericDescription: "Draw an orange animal!"),
        Task(category: .drawing, object: "Crayon", commandPhrase: "a crayon!", genericDescription: "Draw a colorful art tool!"),
        Task(category: .drawing, object: "Crocodile", commandPhrase: "a crocodile!", genericDescription: "Draw a green animal!"),
        Task(category: .drawing, object: "Cruise Ship", commandPhrase: "a cruise ship!", genericDescription: "Draw a moving vacation!"),
        Task(category: .drawing, object: "Cup", commandPhrase: "a cup!", genericDescription: "Draw a container!"),
        Task(category: .drawing, object: "Diamond", commandPhrase: "a diamond!", genericDescription: "Draw an expensive gem!"),
        Task(category: .drawing, object: "Dishwasher", commandPhrase: "a dishwasher!", genericDescription: "Draw an appliance!"),
        Task(category: .drawing, object: "Diving Board", commandPhrase: "a diving board!", genericDescription: "Draw a pool accessory!"),
        Task(category: .drawing, object: "Dog", commandPhrase: "a dog!", genericDescription: "Draw a popular pet!"),
        Task(category: .drawing, object: "Dolphin", commandPhrase: "a dolphin!", genericDescription: "Draw a smart animal!"),
        Task(category: .drawing, object: "Donut", commandPhrase: "a donut!", genericDescription: "Draw a circular snack!"),
        Task(category: .drawing, object: "Dragon", commandPhrase: "a dragon!", genericDescription: "Draw a mythical beast!"),
        Task(category: .drawing, object: "Dresser", commandPhrase: "a dresser!", genericDescription: "Draw a clothing container!"),
        Task(category: .drawing, object: "Drill", commandPhrase: "a drill!", genericDescription: "Draw a building tool!"),
        Task(category: .drawing, object: "Drums", commandPhrase: "drums!", genericDescription: "Draw some percussion!"),
        Task(category: .drawing, object: "Duck", commandPhrase: "a duck!", genericDescription: "Draw a common animal!"),
        Task(category: .drawing, object: "Dumbbell", commandPhrase: "a dumbbell!", genericDescription: "Draw gym equipment!"),
        Task(category: .drawing, object: "Ear", commandPhrase: "an ear!", genericDescription: "Draw a body part on the head!"),
        Task(category: .drawing, object: "Elbow", commandPhrase: "an elbow!", genericDescription: "Draw a part of the arm!"),
        Task(category: .drawing, object: "Elephant", commandPhrase: "an elephant!", genericDescription: "Draw a unique animal!"),
        Task(category: .drawing, object: "Envelope", commandPhrase: "an envelope!", genericDescription: "Draw a paper container!"),
        Task(category: .drawing, object: "Eraser", commandPhrase: "an eraser!", genericDescription: "Draw a part of a pencil!"),
        Task(category: .drawing, object: "Eye", commandPhrase: "an eye!", genericDescription: "Draw a colorful body part!"),
        Task(category: .drawing, object: "Eyeglasses", commandPhrase: "some eyeglasses!", genericDescription: "Draw eye accessories!"),
        Task(category: .drawing, object: "Face", commandPhrase: "a face!", genericDescription: "Draw an important body area!"),
        Task(category: .drawing, object: "Fan", commandPhrase: "a fan!", genericDescription: "Draw a personal coolant!"),
        Task(category: .drawing, object: "Feather", commandPhrase: "a feather!", genericDescription: "Draw something light!"),
        Task(category: .drawing, object: "Fence", commandPhrase: "a fence!", genericDescription: "Draw a barrier!"),
        Task(category: .drawing, object: "Finger", commandPhrase: "a finger!", genericDescription: "Draw a body part you have lots of!"),
        Task(category: .drawing, object: "Fire Hydrant", commandPhrase: "a fire hydrant!", genericDescription: "Draw an emergency water tool!"),
        Task(category: .drawing, object: "Fireplace", commandPhrase: "a fireplace!", genericDescription: "Draw a household hot zone!"),
        Task(category: .drawing, object: "Firetruck", commandPhrase: "a firetruck!", genericDescription: "Draw an emergency vehicle!"),
        Task(category: .drawing, object: "Fish", commandPhrase: "a fish!", genericDescription: "Draw an aquatic animal!"),
        Task(category: .drawing, object: "Flamingo", commandPhrase: "a flamingo!", genericDescription: "Draw a pink animal!"),
        Task(category: .drawing, object: "Flashlight", commandPhrase: "a flashlight!", genericDescription: "Draw an electronic light source!"),
        Task(category: .drawing, object: "Flip Flops", commandPhrase: "some flip flops!", genericDescription: "Draw beach footwear!"),
        Task(category: .drawing, object: "Floor Lamp", commandPhrase: "a floor lamp!", genericDescription: "Draw an indoor light source!"),
        Task(category: .drawing, object: "Flower", commandPhrase: "a flower!", genericDescription: "Draw a common plant!"),
        Task(category: .drawing, object: "Flying Saucer", commandPhrase: "a flying saucer!", genericDescription: "Draw a mythical sky vehicle!"),
        Task(category: .drawing, object: "Foot", commandPhrase: "a foot!", genericDescription: "Draw what you can walk on!"),
        Task(category: .drawing, object: "Fork", commandPhrase: "a fork!", genericDescription: "Draw a utensil!"),
        Task(category: .drawing, object: "Frog", commandPhrase: "a frog!", genericDescription: "Draw a loud animal!"),
        Task(category: .drawing, object: "Frying Pan", commandPhrase: "a frying pan!", genericDescription: "Draw a kitchen item!"),
        Task(category: .drawing, object: "Garden", commandPhrase: "a garden!", genericDescription: "Draw a place with plants!"),
        Task(category: .drawing, object: "Garden Hose", commandPhrase: "a garden hose!", genericDescription: "Draw an outdoor water tool!"),
        Task(category: .drawing, object: "Giraffe", commandPhrase: "a giraffe!", genericDescription: "Draw a tall animal!"),
        Task(category: .drawing, object: "Goatee", commandPhrase: "a goatee!", genericDescription: "Draw a kind of facial hair!"),
        Task(category: .drawing, object: "Golf Club", commandPhrase: "a golf club!", genericDescription: "Draw a long sports tool!"),
        Task(category: .drawing, object: "Grapes", commandPhrase: "some grapes!", genericDescription: "Draw small round fruit!"),
        Task(category: .drawing, object: "Grass", commandPhrase: "some grass!", genericDescription: "Draw a common green plant!"),
        Task(category: .drawing, object: "Guitar", commandPhrase: "a guitar!", genericDescription: "Draw a string instrument!"),
        Task(category: .drawing, object: "Hamburger", commandPhrase: "a hamburger!", genericDescription: "Draw a meat sandwich!"),
        Task(category: .drawing, object: "Hammer", commandPhrase: "a hammer!", genericDescription: "Draw a weapon or building tool!"),
        Task(category: .drawing, object: "Hand", commandPhrase: "a hand!", genericDescription: "Draw what you can type with!"),
        Task(category: .drawing, object: "Harp", commandPhrase: "a harp", genericDescription: "Draw an exotic string instrument!"),
        Task(category: .drawing, object: "Hat", commandPhrase: "a hat!", genericDescription: "Draw a head accessory!"),
        Task(category: .drawing, object: "Headphones", commandPhrase: "some headphones!", genericDescription: "Draw a personal music player!"),
        Task(category: .drawing, object: "Hedgehog", commandPhrase: "a hedgehog!", genericDescription: "Draw a fast blue animal!"),
        Task(category: .drawing, object: "Helicopter", commandPhrase: "a helicopter!", genericDescription: "Draw a flying machine!"),
        Task(category: .drawing, object: "Helmet", commandPhrase: "a helmet!", genericDescription: "Draw brain protection!"),
        Task(category: .drawing, object: "Hexagon", commandPhrase: "a hexagon!", genericDescription: "Draw the shape of 6!"),
        Task(category: .drawing, object: "Hockey Puck", commandPhrase: "a hockey puck!", genericDescription: "Draw a sports disk!"),
        Task(category: .drawing, object: "Hockey Stick", commandPhrase: "a hockey stick!", genericDescription: "Draw a cold sports stick!"),
        Task(category: .drawing, object: "Horse", commandPhrase: "a horse!", genericDescription: "Draw a racing animal!"),
        Task(category: .drawing, object: "Hospital", commandPhrase: "a hospital!", genericDescription: "Draw a life-saving building!"),
        Task(category: .drawing, object: "Hot Air Balloon", commandPhrase: "a hot air balloon!", genericDescription: "Draw an exotic flying machine!"),
        Task(category: .drawing, object: "Hot Dog", commandPhrase: "a hot dog!", genericDescription: "Draw a horizontal food!"),
        Task(category: .drawing, object: "Hot Tub", commandPhrase: "a hot tub!", genericDescription: "Draw a relaxing water container!"),
        Task(category: .drawing, object: "Hourglass", commandPhrase: "an hourglass!", genericDescription: "Draw an exotic timer!"),
        Task(category: .drawing, object: "House", commandPhrase: "a house!", genericDescription: "Draw a dwelling!"),
        Task(category: .drawing, object: "House Plant", commandPhrase: "a house plant!", genericDescription: "Draw a personal plant!"),
        Task(category: .drawing, object: "Hurricane", commandPhrase: "a hurricane!", genericDescription: "Draw a wind storm!"),
        Task(category: .drawing, object: "Feather", commandPhrase: "a feather!", genericDescription: "Draw something light!"),
        Task(category: .drawing, object: "Fence", commandPhrase: "a fence!", genericDescription: "Draw a barrier!"),
        Task(category: .drawing, object: "Finger", commandPhrase: "a finger!", genericDescription: "Draw a body part you have lots of!"),
        Task(category: .drawing, object: "Fire Hydrant", commandPhrase: "a fire hydrant!", genericDescription: "Draw an emergency water tool!"),
        Task(category: .drawing, object: "Fireplace", commandPhrase: "a fireplace!", genericDescription: "Draw a household hot zone!"),
        Task(category: .drawing, object: "Firetruck", commandPhrase: "a firetruck!", genericDescription: "Draw an emergency vehicle!"),
        Task(category: .drawing, object: "Fish", commandPhrase: "a fish!", genericDescription: "Draw an aquatic animal!"),
        Task(category: .drawing, object: "Flamingo", commandPhrase: "a flamingo!", genericDescription: "Draw a pink animal!"),
        Task(category: .drawing, object: "Flashlight", commandPhrase: "a flashlight!", genericDescription: "Draw an electronic light source!"),
        Task(category: .drawing, object: "Flip Flops", commandPhrase: "some flip flops!", genericDescription: "Draw beach footwear!"),
        Task(category: .drawing, object: "Floor Lamp", commandPhrase: "a floor lamp!", genericDescription: "Draw an indoor light source!"),
        Task(category: .drawing, object: "Flower", commandPhrase: "a flower!", genericDescription: "Draw a common plant!"),
        Task(category: .drawing, object: "Flying Saucer", commandPhrase: "a flying saucer!", genericDescription: "Draw a mythical sky vehicle!"),
        Task(category: .drawing, object: "Foot", commandPhrase: "a foot!", genericDescription: "Draw what you can walk on!"),
        Task(category: .drawing, object: "Fork", commandPhrase: "a fork!", genericDescription: "Draw a utensil!"),
        Task(category: .drawing, object: "Frog", commandPhrase: "a frog!", genericDescription: "Draw a loud animal!"),
        Task(category: .drawing, object: "Frying Pan", commandPhrase: "a frying pan!", genericDescription: "Draw a kitchen item!"),
        Task(category: .drawing, object: "Garden", commandPhrase: "a garden!", genericDescription: "Draw a place with plants!"),
        Task(category: .drawing, object: "Garden Hose", commandPhrase: "a garden hose!", genericDescription: "Draw an outdoor water tool!"),
        Task(category: .drawing, object: "Giraffe", commandPhrase: "a giraffe!", genericDescription: "Draw a tall animal!"),
        Task(category: .drawing, object: "Goatee", commandPhrase: "a goatee!", genericDescription: "Draw a kind of facial hair!"),
        Task(category: .drawing, object: "Golf Club", commandPhrase: "a golf club!", genericDescription: "Draw a long sports tool!"),
        Task(category: .drawing, object: "Grapes", commandPhrase: "some grapes!", genericDescription: "Draw small round fruit!"),
        Task(category: .drawing, object: "Grass", commandPhrase: "some grass!", genericDescription: "Draw a common green plant!"),
        Task(category: .drawing, object: "Guitar", commandPhrase: "a guitar!", genericDescription: "Draw a string instrument!"),
        Task(category: .drawing, object: "Hamburger", commandPhrase: "a hamburger!", genericDescription: "Draw a meat sandwich!"),
        Task(category: .drawing, object: "Hammer", commandPhrase: "a hammer!", genericDescription: "Draw a weapon or building tool!"),
        Task(category: .drawing, object: "Hand", commandPhrase: "a hand!", genericDescription: "Draw what you can type with!"),
        Task(category: .drawing, object: "Harp", commandPhrase: "a harp", genericDescription: "Draw an exotic string instrument!"),
        Task(category: .drawing, object: "Hat", commandPhrase: "a hat!", genericDescription: "Draw a head accessory!"),
        Task(category: .drawing, object: "Headphones", commandPhrase: "some headphones!", genericDescription: "Draw a personal music player!"),
        Task(category: .drawing, object: "Hedgehog", commandPhrase: "a hedgehog!", genericDescription: "Draw a fast blue animal!"),
        Task(category: .drawing, object: "Helicopter", commandPhrase: "a helicopter!", genericDescription: "Draw a flying machine!"),
        Task(category: .drawing, object: "Helmet", commandPhrase: "a helmet!", genericDescription: "Draw brain protection!"),
        Task(category: .drawing, object: "Hexagon", commandPhrase: "a hexagon!", genericDescription: "Draw the shape of a stop sign!"),
        Task(category: .drawing, object: "Hockey Puck", commandPhrase: "a hockey puck!", genericDescription: "Draw a sports disk!"),
        Task(category: .drawing, object: "Hockey Stick", commandPhrase: "a hockey stick!", genericDescription: "Draw a cold sports stick!"),
        Task(category: .drawing, object: "Horse", commandPhrase: "a horse!", genericDescription: "Draw a racing animal!"),
        Task(category: .drawing, object: "Hospital", commandPhrase: "a hospital!", genericDescription: "Draw a life-saving building!"),
        Task(category: .drawing, object: "Hot Air Balloon", commandPhrase: "a hot air balloon!", genericDescription: "Draw an exotic flying machine!"),
        Task(category: .drawing, object: "Hot Dog", commandPhrase: "a hot dog!", genericDescription: "Draw a horizontal food!"),
        Task(category: .drawing, object: "Hot Tub", commandPhrase: "a hot tub!", genericDescription: "Draw a relaxing water container!"),
        Task(category: .drawing, object: "Hourglass", commandPhrase: "an hourglass!", genericDescription: "Draw an exotic timer!"),
        Task(category: .drawing, object: "House", commandPhrase: "a house!", genericDescription: "Draw a dwelling!"),
        Task(category: .drawing, object: "House Plant", commandPhrase: "a house plant!", genericDescription: "Draw a personal plant!"),
        Task(category: .drawing, object: "Hurricane", commandPhrase: "a hurricane!", genericDescription: "Draw a wind storm!"),
        Task(category: .drawing, object: "Ice Cream", commandPhrase: "some ice cream!", genericDescription: "Draw a tasty cold treat!"),
        Task(category: .drawing, object: "Jacket", commandPhrase: "a jacket!", genericDescription: "Draw some outerwear!"),
        Task(category: .drawing, object: "Jail", commandPhrase: "a jail!", genericDescription: "Draw involuntary housing!"),
        Task(category: .drawing, object: "Kangaroo", commandPhrase: "a kangaroo!", genericDescription: "Draw an animal down under!"),
        Task(category: .drawing, object: "Key", commandPhrase: "a key!", genericDescription: "Draw a unique valuable!"),
        Task(category: .drawing, object: "Keyboard", commandPhrase: "a keyboard!", genericDescription: "Draw how you write online!"),
        Task(category: .drawing, object: "Knee", commandPhrase: "a knee!", genericDescription: "Draw a part of the leg!"),
        Task(category: .drawing, object: "Knife", commandPhrase: "a knife!", genericDescription: "Draw a weapon and a kitchen tool!"),
        Task(category: .drawing, object: "Ladder", commandPhrase: "a ladder!", genericDescription: "Draw a climbing tool!"),
        Task(category: .drawing, object: "Lantern", commandPhrase: "a lantern!", genericDescription: "Draw a fancy lighting method!"),
        Task(category: .drawing, object: "Laptop", commandPhrase: "a laptop!", genericDescription: "Draw a portable screen!"),
        Task(category: .drawing, object: "Leaf", commandPhrase: "a leaf!", genericDescription: "Draw a plant part!"),
        Task(category: .drawing, object: "Leg", commandPhrase: "a leg!", genericDescription: "Draw how you can walk!"),
        Task(category: .drawing, object: "Light Bulb", commandPhrase: "a light bulb!", genericDescription: "Draw a part of a lamp!"),
        Task(category: .drawing, object: "Lighter", commandPhrase: "a lighter!", genericDescription: "Draw a firestarter!"),
        Task(category: .drawing, object: "Lighthouse", commandPhrase: "a lighthouse!", genericDescription: "Draw a guidance tower!"),
        Task(category: .drawing, object: "Lightning", commandPhrase: "some lightning!", genericDescription: "Draw a product of a storm!"),
        Task(category: .drawing, object: "Line", commandPhrase: "a line!", genericDescription: "Draw where you wait!"),
        Task(category: .drawing, object: "Lion", commandPhrase: "a lion!", genericDescription: "Draw a hairy beast!"),
        Task(category: .drawing, object: "Lipstick", commandPhrase: "some lipstick!", genericDescription: "Draw a kind of makeup!"),
        Task(category: .drawing, object: "Lobster", commandPhrase: "a lobster!", genericDescription: "Draw a common seafood type!"),
        Task(category: .drawing, object: "Lollipop", commandPhrase: "a lollipop!", genericDescription: "Draw a round candy!"),
        Task(category: .drawing, object: "Mailbox", commandPhrase: "a mailbox!", genericDescription: "Draw a box with an address"),
        Task(category: .drawing, object: "Map", commandPhrase: "a map!", genericDescription: "Draw a guiding paper!"),
        Task(category: .drawing, object: "Marker", commandPhrase: "a marker!", genericDescription: "Draw a colorful art tool!"),
        Task(category: .drawing, object: "Matches", commandPhrase: "some matches!", genericDescription: "Draw old-fashioned firestarters"),
        Task(category: .drawing, object: "Megaphone", commandPhrase: "a megaphone!", genericDescription: "Draw a voice amplifier!"),
        Task(category: .drawing, object: "Mermaid", commandPhrase: "a mermaid!", genericDescription: "Draw a mythical sea creature!"),
        Task(category: .drawing, object: "Microphone", commandPhrase: "a microphone!", genericDescription: "Draw a small voice amplifier!"),
        Task(category: .drawing, object: "Microwave", commandPhrase: "a microwave!", genericDescription: "Draw a food heater!"),
        Task(category: .drawing, object: "Monkey", commandPhrase: "a monkey!", genericDescription: "Draw a close relative!"),
        Task(category: .drawing, object: "Moon", commandPhrase: "the Moon!", genericDescription: "Draw a close neighbor!"),
        Task(category: .drawing, object: "Mosquito", commandPhrase: "a mosquito!", genericDescription: "Draw a vampiric pest!"),
        Task(category: .drawing, object: "Motorbike", commandPhrase: "a motorbike!", genericDescription: "Draw a super cool bike!"),
        Task(category: .drawing, object: "Mountain", commandPhrase: "a mountain", genericDescription: "Draw a tall part of nature!"),
        Task(category: .drawing, object: "Mouse", commandPhrase: "a mouse!", genericDescription: "Draw something that likes cheese!"),
        Task(category: .drawing, object: "Moustache", commandPhrase: "a moustache!", genericDescription: "Draw a kind of facial hair!"),
        Task(category: .drawing, object: "Mouth", commandPhrase: "a mouth!", genericDescription: "Draw how you speak!"),
        Task(category: .drawing, object: "Mug", commandPhrase: "a mug!", genericDescription: "Draw a cofee container!"),
        Task(category: .drawing, object: "Mushroom", commandPhrase: "a mushroom!", genericDescription: "Draw a fun guy!"),
        Task(category: .drawing, object: "Nail", commandPhrase: "a nail!", genericDescription: "Draw something sharp!"),
        Task(category: .drawing, object: "Necklace", commandPhrase: "a necklace!", genericDescription: "Draw a neck accessory!"),
        Task(category: .drawing, object: "Nose", commandPhrase: "a nose!", genericDescription: "Draw how you smell!"),
        Task(category: .drawing, object: "Ocean", commandPhrase: "the ocean!", genericDescription: "Draw most of the planet!"),
        Task(category: .drawing, object: "Octagon", commandPhrase: "an octagon!", genericDescription: "Draw a shape with 6 sides!"),
        Task(category: .drawing, object: "Octopus", commandPhrase: "an octopus!", genericDescription: "Draw a sea creature with lots of arms!"),
        Task(category: .drawing, object: "Onion", commandPhrase: "an onion!", genericDescription: "Draw something that causes tears!"),
        Task(category: .drawing, object: "Oven", commandPhrase: "an oven!", genericDescription: "Draw something really hot!"),
        Task(category: .drawing, object: "Owl", commandPhrase: "an owl!", genericDescription: "Draw a nocturnal animal!"),
        Task(category: .drawing, object: "Paintbrush", commandPhrase: "a paintbrush!", genericDescription: "Draw a common art tool!"),
        Task(category: .drawing, object: "Paint Can", commandPhrase: "a paint can!", genericDescription: "Draw an art tool storage device!"),
        Task(category: .drawing, object: "Palm Tree", commandPhrase: "a palm tree!", genericDescription: "Draw a tropical plant!"),
        Task(category: .drawing, object: "Panda", commandPhrase: "a panda!", genericDescription: "Draw a black and white animal!"),
        Task(category: .drawing, object: "Pants", commandPhrase: "a pair of pants!", genericDescription: "Draw a leg accessory!"),
        Task(category: .drawing, object: "Paper Clip", commandPhrase: "a paper clip!", genericDescription: "Draw a very small office essential!"),
        Task(category: .drawing, object: "Parachute", commandPhrase: "a parachute!", genericDescription: "Draw a floating device!"),
        Task(category: .drawing, object: "Parrot", commandPhrase: "a parrot!", genericDescription: "Draw a talking animal!"),
        Task(category: .drawing, object: "Passport", commandPhrase: "a passport!", genericDescription: "Draw a travel essential!"),
        Task(category: .drawing, object: "Peanut", commandPhrase: "a peanut!", genericDescription: "Draw a common allergen!"),
        Task(category: .drawing, object: "Pear", commandPhrase: "a pear!", genericDescription: "Draw a green fruit!"),
        Task(category: .drawing, object: "Peas", commandPhrase: "some peas!", genericDescription: "Draw some small green veggies!"),
        Task(category: .drawing, object: "Pencil", commandPhrase: "a pencil!", genericDescription: "Draw a school essential!"),
        Task(category: .drawing, object: "Penguin", commandPhrase: "a penguin!", genericDescription: "Draw a chilly animal!"),
        Task(category: .drawing, object: "Piano", commandPhrase: "a piano!", genericDescription: "Draw a common instrument!"),
        Task(category: .drawing, object: "Pickup Truck", commandPhrase: "a pickup truck!", genericDescription: "Draw a kind of truck!"),
        Task(category: .drawing, object: "Picture Frame", commandPhrase: "a picture frame!", genericDescription: "Draw a photo holder!"),
        Task(category: .drawing, object: "Pig", commandPhrase: "a pig!", genericDescription: "Draw a pink animal!"),
        Task(category: .drawing, object: "Pillow", commandPhrase: "a pillow!", genericDescription: "Draw a soft headrest!"),
        Task(category: .drawing, object: "Pineapple", commandPhrase: "a pineapple!", genericDescription: "Draw a yellow fruit!"),
        Task(category: .drawing, object: "Pizza", commandPhrase: "a pizza!", genericDescription: "Draw a food with slices!"),
        Task(category: .drawing, object: "Pliers", commandPhrase: "some pliers!", genericDescription: "Draw a pulling tool!"),
        Task(category: .drawing, object: "Police Car", commandPhrase: "a police car!", genericDescription: "Draw a vehicle with sirens!"),
        Task(category: .drawing, object: "Pond", commandPhrase: "a pond!", genericDescription: "Draw a smaller lake!"),
        Task(category: .drawing, object: "Popsicle", commandPhrase: "a popsicle!", genericDescription: "Draw a colorful cold treat!"),
        Task(category: .drawing, object: "Postcard", commandPhrase: "a postcard!", genericDescription: "Draw vacation mail!"),
        Task(category: .drawing, object: "Potato", commandPhrase: "a potato!", genericDescription: "Draw what french fries are made of!"),
        Task(category: .drawing, object: "Power Outlet", commandPhrase: "a power outlet!", genericDescription: "Draw where to plug in!"),
        Task(category: .drawing, object: "Purse", commandPhrase: "a purse!", genericDescription: "Draw portable storage!"),
        Task(category: .drawing, object: "Rabbit", commandPhrase: "a rabbit!", genericDescription: "Draw a magic animal!"),
        Task(category: .drawing, object: "Raccoon", commandPhrase: "a raccoon!", genericDescription: "Draw a trashy animal!"),
        Task(category: .drawing, object: "Radio", commandPhrase: "a radio!", genericDescription: "Draw a speaker with stations!"),
        Task(category: .drawing, object: "Rain", commandPhrase: "rain!", genericDescription: "Draw a product of a storm!"),
        Task(category: .drawing, object: "Rainbow", commandPhrase: "a rainbow!", genericDescription: "Draw all the colors!"),
        Task(category: .drawing, object: "Rake", commandPhrase: "a rake!", genericDescription: "Draw a leaf manager!"),
        Task(category: .drawing, object: "Remote Control", commandPhrase: "a remote control!", genericDescription: "Draw a TV manager!"),
        Task(category: .drawing, object: "Rhinoceros", commandPhrase: "a rhinoceros!", genericDescription: "Draw an animal with a horn!"),
        Task(category: .drawing, object: "Rifle", commandPhrase: "a rifle!", genericDescription: "Draw a weapon!"),
        Task(category: .drawing, object: "River", commandPhrase: "a river!", genericDescription: "Draw moving water!"),
        Task(category: .drawing, object: "Roller Coaster", commandPhrase: "a roller coaster!", genericDescription: "Draw a fast ride!"),
        Task(category: .drawing, object: "Rollerskates", commandPhrase: "some rollerskates!", genericDescription: "Draw mobile footwear!"),
        Task(category: .drawing, object: "Sailboat", commandPhrase: "a sailboat!", genericDescription: "Draw an old-style boat!"),
        Task(category: .drawing, object: "Sandwich", commandPhrase: "a sandwich!", genericDescription: "Draw a customizable food!"),
        Task(category: .drawing, object: "Saw", commandPhrase: "a saw!", genericDescription: "Draw a sharp tool!"),
        Task(category: .drawing, object: "Saxophone", commandPhrase: "a saxophone!", genericDescription: "Draw a sexy instrument!"),
        Task(category: .drawing, object: "School Bus", commandPhrase: "a school bus!", genericDescription: "Draw a yellow vehicle!"),
        Task(category: .drawing, object: "Scissors", commandPhrase: "some scissors!", genericDescription: "Draw a household sharp tool!"),
        Task(category: .drawing, object: "Scorpion", commandPhrase: "a scorpion", genericDescription: "Draw a sharp animal!"),
        Task(category: .drawing, object: "Screwdriver", commandPhrase: "a screwdriver!", genericDescription: "Draw an essential household tool!"),
        Task(category: .drawing, object: "Sea Turtle", commandPhrase: "a sea turtle!", genericDescription: "Draw a green aquatic animal!"),
        Task(category: .drawing, object: "See Saw", commandPhrase: "a see saw!", genericDescription: "Draw a playground bar!"),
        Task(category: .drawing, object: "Shark", commandPhrase: "a shark!", genericDescription: "Draw a scary underwater animal!"),
        Task(category: .drawing, object: "Sheep", commandPhrase: "a sheep!", genericDescription: "Draw a soft farm animal!"),
        Task(category: .drawing, object: "Shoe", commandPhrase: "a shoe!", genericDescription: "Draw a foot accessory!"),
        Task(category: .drawing, object: "Shorts", commandPhrase: "some shorts!", genericDescription: "Draw a leg accessory!"),
        Task(category: .drawing, object: "Shovel", commandPhrase: "a shovel!", genericDescription: "Draw a digging tool!"),
        Task(category: .drawing, object: "Sink", commandPhrase: "a sink!", genericDescription: "Draw a wet place from the bathroom!"),
        Task(category: .drawing, object: "Skateboard", commandPhrase: "a skateboard!", genericDescription: "Draw a personal rolling device!"),
        Task(category: .drawing, object: "Sleeping Bag", commandPhrase: "a sleeping bag!", genericDescription: "Draw a portable bed!"),
        Task(category: .drawing, object: "Skull", commandPhrase: "a skull!", genericDescription: "Draw part of a skeleton!"),
        Task(category: .drawing, object: "Skyscraper", commandPhrase: "a skyscraper!", genericDescription: "Draw a tall place!"),
        Task(category: .drawing, object: "Smiley Face", commandPhrase: "a smiley face!", genericDescription: "Draw a happy emoji!"),
        Task(category: .drawing, object: "Snail", commandPhrase: "a snail!", genericDescription: "Draw a slow animal!"),
        Task(category: .drawing, object: "Snake", commandPhrase: "a snake!", genericDescription: "Draw a long animal!"),
        Task(category: .drawing, object: "Snorkel", commandPhrase: "a snorkel!", genericDescription: "Draw underwater eyewear!"),
        Task(category: .drawing, object: "Snowflake", commandPhrase: "a snowflake!", genericDescription: "Draw something cold and unique!"),
        Task(category: .drawing, object: "Snowman", commandPhrase: "a snowman!", genericDescription: "Draw someone cold!"),
        Task(category: .drawing, object: "Soccer Ball", commandPhrase: "a soccer ball!", genericDescription: "Draw a black and white sports object!"),
        Task(category: .drawing, object: "Sock", commandPhrase: "a sock!", genericDescription: "Draw a foot accessory!"),
        Task(category: .drawing, object: "Speedboat", commandPhrase: "a speedboat!", genericDescription: "Draw a fast kind of boat!"),
        Task(category: .drawing, object: "Spider", commandPhrase: "a spider!", genericDescription: "Draw a scary insect!"),
        Task(category: .drawing, object: "Spoon", commandPhrase: "a spoon!", genericDescription: "Draw a kitchen utensil!"),
        Task(category: .drawing, object: "Spreadsheet", commandPhrase: "a spreadsheet!", genericDescription: "Draw a fancy kind of table!"),
        Task(category: .drawing, object: "Square", commandPhrase: "a square!", genericDescription: "Draw a very basic shape!"),
        Task(category: .drawing, object: "Squiggle", commandPhrase: "a squiggle!", genericDescription: "Draw a curvy line!"),
        Task(category: .drawing, object: "Stairs", commandPhrase: "some stairs!", genericDescription: "Draw how to ascend somewhere!"),
        Task(category: .drawing, object: "Star", commandPhrase: "a star!", genericDescription: "Draw something really, really, really hot!"),
        Task(category: .drawing, object: "Steak", commandPhrase: "a steak!", genericDescription: "Draw what a cow becomes!"),
        Task(category: .drawing, object: "Stereo", commandPhrase: "a stereo!", genericDescription: "Draw a fancy speaker!"),
        Task(category: .drawing, object: "Stethoscope", commandPhrase: "a stethoscope!", genericDescription: "Draw a doctor's headphones!"),
        Task(category: .drawing, object: "Stitches", commandPhrase: "some stitches!", genericDescription: "Draw advanced bandages!"),
        Task(category: .drawing, object: "Stop Sign", commandPhrase: "a stop sign!", genericDescription: "Draw a red octagon!"),
        Task(category: .drawing, object: "Stove", commandPhrase: "a stove!", genericDescription: "Draw something you shouldn't leave on!"),
        Task(category: .drawing, object: "Strawberry", commandPhrase: "a strawberry!", genericDescription: "Draw a small red fruit!"),
        Task(category: .drawing, object: "Streetlight", commandPhrase: "a streetlight!", genericDescription: "Draw an outdoor light source!"),
        Task(category: .drawing, object: "String Bean", commandPhrase: "a string bean!", genericDescription: "Draw a unique kind of bean!"),
        Task(category: .drawing, object: "Submarine", commandPhrase: "a submarine!", genericDescription: "Draw an underwater car!"),
        Task(category: .drawing, object: "Suitcase", commandPhrase: "a suitcase!", genericDescription: "Draw a travel companion!"),
        Task(category: .drawing, object: "Sun", commandPhrase: "the Sun!", genericDescription: "Draw our biggest light source!"),
        Task(category: .drawing, object: "Swan", commandPhrase: "a swan!", genericDescription: "Draw a majestic white bird!"),
        Task(category: .drawing, object: "Sweater", commandPhrase: "a sweater!", genericDescription: "Draw a cozy shirt!"),
        Task(category: .drawing, object: "Swing Set", commandPhrase: "a swing set!", genericDescription: "Draw an essential playground installation!"),
        Task(category: .drawing, object: "Sword", commandPhrase: "a sword!", genericDescription: "Draw a classic hero weapon!"),
        Task(category: .drawing, object: "Syringe", commandPhrase: "a syringe!", genericDescription: "Draw a medicine delivery tool!"),
        Task(category: .drawing, object: "Table", commandPhrase: "a table!", genericDescription: "Draw something for placing upon!"),
        Task(category: .drawing, object: "Teapot", commandPhrase: "a teapot!", genericDescription: "Draw a fancy liquid storage device!"),
        Task(category: .drawing, object: "Teddy-Bear", commandPhrase: "a teddy-bear!", genericDescription: "Draw a cuddly bedtime friend!"),
        Task(category: .drawing, object: "Telephone", commandPhrase: "a telephone!", genericDescription: "Draw how to chat from afar!"),
        Task(category: .drawing, object: "Television", commandPhrase: "a television!", genericDescription: "Draw how to see from afar!"),
        Task(category: .drawing, object: "Tennis Racquet", commandPhrase: "a tennis racquet!", genericDescription: "Draw a ball hitter!"),
        Task(category: .drawing, object: "Tent", commandPhrase: "a tent!", genericDescription: "Draw a portable house!"),
        Task(category: .drawing, object: "Tiger", commandPhrase: "a tiger!", genericDescription: "Draw a big cat!"),
        Task(category: .drawing, object: "Toaster", commandPhrase: "a toaster!", genericDescription: "Draw a kitchen item with levers!"),
        Task(category: .drawing, object: "Toe", commandPhrase: "a toe!", genericDescription: "Draw a feature of feet!"),
        Task(category: .drawing, object: "Toilet", commandPhrase: "a toilet!", genericDescription: "Draw a very private place!"),
        Task(category: .drawing, object: "Tooth", commandPhrase: "a tooth!", genericDescription: "Draw what you brush!"),
        Task(category: .drawing, object: "Toothbrush", commandPhrase: "a toothbrush!", genericDescription: "Draw a brushing stick!"),
        Task(category: .drawing, object: "Tornado", commandPhrase: "a tornado!", genericDescription: "Draw swirling winds!"),
        Task(category: .drawing, object: "Tractor", commandPhrase: "a tractor!", genericDescription: "Draw a classic farm vehicle!"),
        Task(category: .drawing, object: "Toothpaste", commandPhrase: "some toothpaste!", genericDescription: "Draw what you brush with!"),
        Task(category: .drawing, object: "Traffic Light", commandPhrase: "a traffic light!", genericDescription: "Draw an electronic sign!"),
        Task(category: .drawing, object: "Train", commandPhrase: "a train!", genericDescription: "Draw a group of moving cars!"),
        Task(category: .drawing, object: "Tree", commandPhrase: "a tree!", genericDescription: "Draw a tall plant!"),
        Task(category: .drawing, object: "Triangle", commandPhrase: "a triangle!", genericDescription: "Draw a strong basic shape!"),
        Task(category: .drawing, object: "Trombone", commandPhrase: "a trombone!", genericDescription: "Draw a sliding instrument!"),
        Task(category: .drawing, object: "Truck", commandPhrase: "a truck!", genericDescription: "Draw a big car!"),
        Task(category: .drawing, object: "Trumpet", commandPhrase: "a trumpet!", genericDescription: "Draw an instrument with valves!"),
        Task(category: .drawing, object: "T-Shirt", commandPhrase: "a T-Shirt!", genericDescription: "Draw classic top wear!"),
        Task(category: .drawing, object: "Umbrella", commandPhrase: "an umbrella!", genericDescription: "Draw a moisture negator!"),
        Task(category: .drawing, object: "Underwear", commandPhrase: "a pair of underwear!", genericDescription: "Draw what's under there!"),
        Task(category: .drawing, object: "Van", commandPhrase: "a van!", genericDescription: "Draw a wide car!"),
        Task(category: .drawing, object: "Vase", commandPhrase: "a vase!", genericDescription: "Draw a fancy pot!"),
        Task(category: .drawing, object: "Violin", commandPhrase: "a violin!", genericDescription: "Draw a classic orchestra instrument!"),
        Task(category: .drawing, object: "Washing Machine", commandPhrase: "a washing machine!", genericDescription: "Draw a clothing appliance!"),
        Task(category: .drawing, object: "Watermelon", commandPhrase: "a watermelon!", genericDescription: "Draw a big fruit with seeds!"),
        Task(category: .drawing, object: "Waterslide", commandPhrase: "a waterslide!", genericDescription: "Draw a waterpark staple!"),
        Task(category: .drawing, object: "Whale", commandPhrase: "a whale!", genericDescription: "Draw the biggest animal!"),
        Task(category: .drawing, object: "Wheel", commandPhrase: "a wheel!", genericDescription: "Draw what makes cars go!"),
        Task(category: .drawing, object: "Windmill", commandPhrase: "a windmill!", genericDescription: "Draw clean energy generation!"),
        Task(category: .drawing, object: "Wine Bottle", commandPhrase: "a wine bottle!", genericDescription: "Draw a container for specific alcohol!"),
        Task(category: .drawing, object: "Wine Glass", commandPhrase: "a wine glass!", genericDescription: "Draw a fancy container for alcohol!"),
        Task(category: .drawing, object: "Wristwatch", commandPhrase: "a wristwatch!", genericDescription: "Draw a portable clock!"),
        Task(category: .drawing, object: "Yoga", commandPhrase: "some yoga!", genericDescription: "Draw a flexible pose!"),
        Task(category: .drawing, object: "Zebra", commandPhrase: "a zebra!", genericDescription: "Draw a striped animal!"),
        Task(category: .drawing, object: "Zigzag", commandPhrase: "a zigzag!", genericDescription: "Draw a funky line!"),
        Task(category: .drawing, object: "Bird", commandPhrase: "a bird!", genericDescription: "Draw something that flies!"),
        Task(category: .drawing, object: "Bowtie", commandPhrase: "a bowtie!", genericDescription: "Draw a fancy accessory!"),
        Task(category: .drawing, object: "Broom", commandPhrase: "a broom!", genericDescription: "Draw something that cleans!"),
        Task(category: .drawing, object: "Calculator", commandPhrase: "a calculator!", genericDescription: "Draw a common math tool!"),
        Task(category: .drawing, object: "Cat", commandPhrase: "a cat!", genericDescription: "Draw a common pet!"),
        Task(category: .drawing, object: "Crown", commandPhrase: "a crown!", genericDescription: "Draw a piece of expensive headwear!"),
        Task(category: .drawing, object: "Clock", commandPhrase: "a clock!", genericDescription: "Draw something round with hands!"),
        Task(category: .drawing, object: "Door", commandPhrase: "a door!", genericDescription: "Draw something that opens!")
    ]
    
}
