//
// Drawing_Judge_Model.swift
//
// This file was originally generated by Xcode for the Drawing Judge model and extended to load any of the Ultra Drawing Judge models.
//

import CoreML


/// Model Prediction Input Type
nonisolated class Drawing_Judge_ModelInput : MLFeatureProvider {

    /// Input image to be classified as color (kCVPixelFormatType_32BGRA) image buffer, 299 pixels wide by 299 pixels high
    var image: CVPixelBuffer

    var featureNames: Set<String> {
        get {
            return ["image"]
        }
    }
    
    func featureValue(for featureName: String) -> MLFeatureValue? {
        if (featureName == "image") {
            return MLFeatureValue(pixelBuffer: image)
        }
        return nil
    }
    
    init(image: CVPixelBuffer) {
        self.image = image
    }

    convenience init(imageWith image: CGImage) throws {
        self.init(image: try MLFeatureValue(cgImage: image, pixelsWide: 299, pixelsHigh: 299, pixelFormatType: kCVPixelFormatType_32BGRA, options: nil).imageBufferValue!)
    }

    convenience init(imageAt image: URL) throws {
        self.init(image: try MLFeatureValue(imageAt: image, pixelsWide: 299, pixelsHigh: 299, pixelFormatType: kCVPixelFormatType_32BGRA, options: nil).imageBufferValue!)
    }

    func setImage(with image: CGImage) throws  {
        self.image = try MLFeatureValue(cgImage: image, pixelsWide: 299, pixelsHigh: 299, pixelFormatType: kCVPixelFormatType_32BGRA, options: nil).imageBufferValue!
    }

    func setImage(with image: URL) throws  {
        self.image = try MLFeatureValue(imageAt: image, pixelsWide: 299, pixelsHigh: 299, pixelFormatType: kCVPixelFormatType_32BGRA, options: nil).imageBufferValue!
    }

}


/// Model Prediction Output Type
nonisolated class Drawing_Judge_ModelOutput : MLFeatureProvider {

    /// Source provided by CoreML
    private let provider : MLFeatureProvider

    /// Probability of each category as dictionary of strings to doubles
    lazy var classLabelProbs: [String : Double] = {
        [unowned self] in return self.provider.featureValue(for: "classLabelProbs")!.dictionaryValue as! [String : Double]
    }()

    /// Most likely image category as string value
    lazy var classLabel: String = {
        [unowned self] in return self.provider.featureValue(for: "classLabel")!.stringValue
    }()

    var featureNames: Set<String> {
        return self.provider.featureNames
    }
    
    func featureValue(for featureName: String) -> MLFeatureValue? {
        return self.provider.featureValue(for: featureName)
    }

    init(classLabelProbs: [String : Double], classLabel: String) {
        self.provider = try! MLDictionaryFeatureProvider(dictionary: ["classLabelProbs" : MLFeatureValue(dictionary: classLabelProbs as [AnyHashable : NSNumber]), "classLabel" : MLFeatureValue(string: classLabel)])
    }

    init(features: MLFeatureProvider) {
        self.provider = features
    }
}


/// Class for model loading and prediction
nonisolated class Drawing_Judge_Model {
    let model: MLModel

    /// URL of model assuming it was installed in the same bundle as this class
    class var urlOfModelInThisBundle : URL {
        let bundle = Bundle(for: self)
        return bundle.url(forResource: "Drawing Judge", withExtension: "mlmodelc")!
    }

    /**
        Construct Drawing_Judge_Model instance with an existing MLModel object.

        Usually the application does not use this initializer unless it makes a subclass of Drawing_Judge_Model.
        Such application may want to use `MLModel(contentsOfURL:configuration:)` and `Drawing_Judge_Model.urlOfModelInThisBundle` to create a MLModel object to pass-in.

        - parameters:
          - model: MLModel object
    */
    init(model: MLModel) {
        self.model = model
    }

    /**
        Construct a model with configuration

        - parameters:
           - configuration: the desired model configuration

        - throws: an NSError object that describes the problem
    */
    convenience init(configuration: MLModelConfiguration) throws {
        try self.init(contentsOf: type(of:self).urlOfModelInThisBundle, configuration: configuration)
    }
    
    /**
        Construct a model from a configuration and with a custom Ultra Drawing Judge model.

        - parameters:
           - configuration: the desired model configuration
           - ultraDrawingJudgeModel: The Ultra Drawing Judge model to use.

        - throws: an NSError object that describes the problem
    */
    convenience init(configuration: MLModelConfiguration, ultraDrawingJudgeModel: UltraDrawingJudgeModel) throws {
        // Get the URL to the specified model file
        guard let modelURL = Bundle.main.url(forResource: ultraDrawingJudgeModel.resourceName, withExtension: "mlmodelc") else {
            throw CocoaError(.fileNoSuchFile, userInfo: [NSFilePathErrorKey: ultraDrawingJudgeModel.resourceName])
        }
        
        // Continue the instantiation process with this URL instead of the default
        try self.init(contentsOf: modelURL, configuration: configuration)
    }

    /**
        Construct Drawing_Judge_Model instance with explicit path to mlmodelc file
        - parameters:
           - modelURL: the file url of the model

        - throws: an NSError object that describes the problem
    */
    convenience init(contentsOf modelURL: URL) throws {
        try self.init(model: MLModel(contentsOf: modelURL))
    }

    /**
        Construct a model with URL of the .mlmodelc directory and configuration

        - parameters:
           - modelURL: the file url of the model
           - configuration: the desired model configuration

        - throws: an NSError object that describes the problem
    */
    convenience init(contentsOf modelURL: URL, configuration: MLModelConfiguration) throws {
        try self.init(model: MLModel(contentsOf: modelURL, configuration: configuration))
    }

    /**
        Make a prediction using the structured interface

        - parameters:
           - input: the input to the prediction as Drawing_Judge_ModelInput

        - throws: an NSError object that describes the problem

        - returns: the result of the prediction as Drawing_Judge_ModelOutput
    */
    func prediction(input: Drawing_Judge_ModelInput) throws -> Drawing_Judge_ModelOutput {
        return try self.prediction(input: input, options: MLPredictionOptions())
    }

    /**
        Make a prediction using the structured interface

        - parameters:
           - input: the input to the prediction as Drawing_Judge_ModelInput
           - options: prediction options

        - throws: an NSError object that describes the problem

        - returns: the result of the prediction as Drawing_Judge_ModelOutput
    */
    func prediction(input: Drawing_Judge_ModelInput, options: MLPredictionOptions) throws -> Drawing_Judge_ModelOutput {
        let outFeatures = try model.prediction(from: input, options:options)
        return Drawing_Judge_ModelOutput(features: outFeatures)
    }

    /**
        Make a prediction using the convenience interface

        - parameters:
            - image: Input image to be classified as color (kCVPixelFormatType_32BGRA) image buffer, 299 pixels wide by 299 pixels high

        - throws: an NSError object that describes the problem

        - returns: the result of the prediction as Drawing_Judge_ModelOutput
    */
    func prediction(image: CVPixelBuffer) throws -> Drawing_Judge_ModelOutput {
        let input_ = Drawing_Judge_ModelInput(image: image)
        return try self.prediction(input: input_)
    }

    /**
        Make a batch prediction using the structured interface

        - parameters:
           - inputs: the inputs to the prediction as [Drawing_Judge_ModelInput]
           - options: prediction options

        - throws: an NSError object that describes the problem

        - returns: the result of the prediction as [Drawing_Judge_ModelOutput]
    */
    func predictions(inputs: [Drawing_Judge_ModelInput], options: MLPredictionOptions = MLPredictionOptions()) throws -> [Drawing_Judge_ModelOutput] {
        let batchIn = MLArrayBatchProvider(array: inputs)
        let batchOut = try model.predictions(from: batchIn, options: options)
        var results : [Drawing_Judge_ModelOutput] = []
        results.reserveCapacity(inputs.count)
        for i in 0..<batchOut.count {
            let outProvider = batchOut.features(at: i)
            let result =  Drawing_Judge_ModelOutput(features: outProvider)
            results.append(result)
        }
        return results
    }
}
